# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Editor2.ui'
#
# Created: Fri May 16 23:07:39 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Editor2(object):
    def setupUi(self, Editor2):
        Editor2.setObjectName(_fromUtf8("Editor2"))
        Editor2.resize(774, 478)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Nimbus Sans L"))
        Editor2.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/icono.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Editor2.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(Editor2)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.Trabajo = QtGui.QGridLayout(self.centralwidget)
        self.Trabajo.setContentsMargins(-1, -1, -1, 9)
        self.Trabajo.setHorizontalSpacing(6)
        self.Trabajo.setVerticalSpacing(0)
        self.Trabajo.setObjectName(_fromUtf8("Trabajo"))
        self.tabs = QtGui.QTabWidget(self.centralwidget)
        self.tabs.setEnabled(True)
        self.tabs.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tabs.setDocumentMode(True)
        self.tabs.setMovable(True)
        self.tabs.setObjectName(_fromUtf8("tabs"))
        self.editor = QtGui.QWidget()
        self.editor.setObjectName(_fromUtf8("editor"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.editor)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.editando = QtGui.QTextEdit(self.editor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editando.sizePolicy().hasHeightForWidth())
        self.editando.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Nimbus Sans L"))
        self.editando.setFont(font)
        self.editando.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.editando.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.editando.setFrameShape(QtGui.QFrame.HLine)
        self.editando.setFrameShadow(QtGui.QFrame.Sunken)
        self.editando.setTabStopWidth(32)
        self.editando.setAcceptRichText(False)
        self.editando.setObjectName(_fromUtf8("editando"))
        self.horizontalLayout.addWidget(self.editando)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/archivo.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tabs.addTab(self.editor, icon1, _fromUtf8(""))
        self.vistapreliminar = QtGui.QWidget()
        self.vistapreliminar.setObjectName(_fromUtf8("vistapreliminar"))
        self.gridLayout_3 = QtGui.QGridLayout(self.vistapreliminar)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.vistaHtml1 = QtWebKit.QWebView(self.vistapreliminar)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Nimbus Sans L"))
        self.vistaHtml1.setFont(font)
        self.vistaHtml1.setProperty("url", QtCore.QUrl(_fromUtf8("file:///home/mateo/Escritorio/MarkYoun! v0.4 beta/Help/Ayuda.md.html")))
        self.vistaHtml1.setObjectName(_fromUtf8("vistaHtml1"))
        self.gridLayout_3.addWidget(self.vistaHtml1, 0, 0, 1, 1)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/Ayuda.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tabs.addTab(self.vistapreliminar, icon2, _fromUtf8(""))
        self.Trabajo.addWidget(self.tabs, 1, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_2.addWidget(self.line, 0, 2, 1, 1)
        self.seleccionFormato = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.seleccionFormato.sizePolicy().hasHeightForWidth())
        self.seleccionFormato.setSizePolicy(sizePolicy)
        self.seleccionFormato.setMaximumSize(QtCore.QSize(82, 26))
        self.seleccionFormato.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.seleccionFormato.setFocusPolicy(QtCore.Qt.NoFocus)
        self.seleccionFormato.setObjectName(_fromUtf8("seleccionFormato"))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/formato.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.seleccionFormato.addItem(icon3, _fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/linea.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.seleccionFormato.addItem(icon4, _fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/Negrita.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.seleccionFormato.addItem(icon5, _fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/Cursiva.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.seleccionFormato.addItem(icon6, _fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/underline.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.seleccionFormato.addItem(icon7, _fromUtf8(""))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/tachado.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.seleccionFormato.addItem(icon8, _fromUtf8(""))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/big.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.seleccionFormato.addItem(icon9, _fromUtf8(""))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/small.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.seleccionFormato.addItem(icon10, _fromUtf8(""))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/superindice.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.seleccionFormato.addItem(icon11, _fromUtf8(""))
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/subindice.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.seleccionFormato.addItem(icon12, _fromUtf8(""))
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/br.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.seleccionFormato.addItem(icon13, _fromUtf8(""))
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/izquierda.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.seleccionFormato.addItem(icon14, _fromUtf8(""))
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/derecha.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.seleccionFormato.addItem(icon15, _fromUtf8(""))
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/centrado.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.seleccionFormato.addItem(icon16, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.seleccionFormato, 0, 1, 1, 1)
        self.seleccionLinea = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.seleccionLinea.sizePolicy().hasHeightForWidth())
        self.seleccionLinea.setSizePolicy(sizePolicy)
        self.seleccionLinea.setMaximumSize(QtCore.QSize(128, 26))
        self.seleccionLinea.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.seleccionLinea.setFocusPolicy(QtCore.Qt.NoFocus)
        self.seleccionLinea.setObjectName(_fromUtf8("seleccionLinea"))
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/lineaF.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.seleccionLinea.addItem(icon17, _fromUtf8(""))
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/H1.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.seleccionLinea.addItem(icon18, _fromUtf8(""))
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/H2.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.seleccionLinea.addItem(icon19, _fromUtf8(""))
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/H3.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.seleccionLinea.addItem(icon20, _fromUtf8(""))
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/cita.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.seleccionLinea.addItem(icon21, _fromUtf8(""))
        self.seleccionLinea.addItem(icon21, _fromUtf8(""))
        self.seleccionLinea.addItem(icon21, _fromUtf8(""))
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/codigo.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.seleccionLinea.addItem(icon22, _fromUtf8(""))
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/listaN.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.seleccionLinea.addItem(icon23, _fromUtf8(""))
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/lista.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.seleccionLinea.addItem(icon24, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.seleccionLinea, 0, 0, 1, 1)
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout_2.addWidget(self.line_2, 0, 7, 1, 1)
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout_2.addWidget(self.line_3, 0, 4, 1, 1)
        self.guardar = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.guardar.sizePolicy().hasHeightForWidth())
        self.guardar.setSizePolicy(sizePolicy)
        self.guardar.setMinimumSize(QtCore.QSize(32, 32))
        self.guardar.setMaximumSize(QtCore.QSize(32, 32))
        self.guardar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.guardar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.guardar.setText(_fromUtf8(""))
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/Guardar.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.guardar.setIcon(icon25)
        self.guardar.setIconSize(QtCore.QSize(26, 26))
        self.guardar.setAutoDefault(False)
        self.guardar.setDefault(False)
        self.guardar.setFlat(True)
        self.guardar.setObjectName(_fromUtf8("guardar"))
        self.gridLayout_2.addWidget(self.guardar, 0, 3, 1, 1)
        self.html = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.html.sizePolicy().hasHeightForWidth())
        self.html.setSizePolicy(sizePolicy)
        self.html.setMinimumSize(QtCore.QSize(32, 32))
        self.html.setMaximumSize(QtCore.QSize(32, 32))
        self.html.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.html.setFocusPolicy(QtCore.Qt.NoFocus)
        self.html.setText(_fromUtf8(""))
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/utilidad.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.html.setIcon(icon26)
        self.html.setIconSize(QtCore.QSize(26, 26))
        self.html.setAutoDefault(False)
        self.html.setDefault(False)
        self.html.setFlat(True)
        self.html.setObjectName(_fromUtf8("html"))
        self.gridLayout_2.addWidget(self.html, 0, 6, 1, 1)
        self.link = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.link.sizePolicy().hasHeightForWidth())
        self.link.setSizePolicy(sizePolicy)
        self.link.setMinimumSize(QtCore.QSize(32, 32))
        self.link.setMaximumSize(QtCore.QSize(32, 32))
        self.link.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.link.setFocusPolicy(QtCore.Qt.NoFocus)
        self.link.setText(_fromUtf8(""))
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/imagen.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.link.setIcon(icon27)
        self.link.setIconSize(QtCore.QSize(26, 26))
        self.link.setAutoDefault(False)
        self.link.setDefault(False)
        self.link.setFlat(True)
        self.link.setObjectName(_fromUtf8("link"))
        self.gridLayout_2.addWidget(self.link, 0, 5, 1, 1)
        self.aPdf = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.aPdf.sizePolicy().hasHeightForWidth())
        self.aPdf.setSizePolicy(sizePolicy)
        self.aPdf.setMinimumSize(QtCore.QSize(32, 32))
        self.aPdf.setMaximumSize(QtCore.QSize(32, 32))
        self.aPdf.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.aPdf.setFocusPolicy(QtCore.Qt.NoFocus)
        self.aPdf.setText(_fromUtf8(""))
        icon28 = QtGui.QIcon()
        icon28.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/aPdf.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.aPdf.setIcon(icon28)
        self.aPdf.setIconSize(QtCore.QSize(26, 26))
        self.aPdf.setAutoDefault(False)
        self.aPdf.setDefault(False)
        self.aPdf.setFlat(True)
        self.aPdf.setObjectName(_fromUtf8("aPdf"))
        self.gridLayout_2.addWidget(self.aPdf, 0, 9, 1, 1)
        self.aOdt = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.aOdt.sizePolicy().hasHeightForWidth())
        self.aOdt.setSizePolicy(sizePolicy)
        self.aOdt.setMinimumSize(QtCore.QSize(32, 32))
        self.aOdt.setMaximumSize(QtCore.QSize(32, 32))
        self.aOdt.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.aOdt.setFocusPolicy(QtCore.Qt.NoFocus)
        self.aOdt.setText(_fromUtf8(""))
        icon29 = QtGui.QIcon()
        icon29.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/aOdt.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.aOdt.setIcon(icon29)
        self.aOdt.setIconSize(QtCore.QSize(26, 26))
        self.aOdt.setAutoDefault(False)
        self.aOdt.setDefault(False)
        self.aOdt.setFlat(True)
        self.aOdt.setObjectName(_fromUtf8("aOdt"))
        self.gridLayout_2.addWidget(self.aOdt, 0, 10, 1, 1)
        self.aEpub = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.aEpub.sizePolicy().hasHeightForWidth())
        self.aEpub.setSizePolicy(sizePolicy)
        self.aEpub.setMinimumSize(QtCore.QSize(32, 32))
        self.aEpub.setMaximumSize(QtCore.QSize(32, 32))
        self.aEpub.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.aEpub.setFocusPolicy(QtCore.Qt.NoFocus)
        self.aEpub.setText(_fromUtf8(""))
        icon30 = QtGui.QIcon()
        icon30.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/aEpub.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.aEpub.setIcon(icon30)
        self.aEpub.setIconSize(QtCore.QSize(26, 26))
        self.aEpub.setAutoDefault(False)
        self.aEpub.setDefault(False)
        self.aEpub.setFlat(True)
        self.aEpub.setObjectName(_fromUtf8("aEpub"))
        self.gridLayout_2.addWidget(self.aEpub, 0, 11, 1, 1)
        self.aHtml = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.aHtml.sizePolicy().hasHeightForWidth())
        self.aHtml.setSizePolicy(sizePolicy)
        self.aHtml.setMinimumSize(QtCore.QSize(32, 32))
        self.aHtml.setMaximumSize(QtCore.QSize(32, 32))
        self.aHtml.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.aHtml.setFocusPolicy(QtCore.Qt.NoFocus)
        self.aHtml.setText(_fromUtf8(""))
        icon31 = QtGui.QIcon()
        icon31.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/aHtml.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.aHtml.setIcon(icon31)
        self.aHtml.setIconSize(QtCore.QSize(26, 26))
        self.aHtml.setAutoDefault(False)
        self.aHtml.setDefault(False)
        self.aHtml.setFlat(True)
        self.aHtml.setObjectName(_fromUtf8("aHtml"))
        self.gridLayout_2.addWidget(self.aHtml, 0, 8, 1, 1)
        self.line_4 = QtGui.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout_2.addWidget(self.line_4, 0, 12, 1, 1)
        self.url = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.url.sizePolicy().hasHeightForWidth())
        self.url.setSizePolicy(sizePolicy)
        self.url.setMinimumSize(QtCore.QSize(0, 0))
        self.url.setMaximumSize(QtCore.QSize(680, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(107, 107, 107))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(107, 107, 107))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(153, 153, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.url.setPalette(palette)
        self.url.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.url.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.url.setText(_fromUtf8(""))
        self.url.setFrame(False)
        self.url.setReadOnly(True)
        self.url.setObjectName(_fromUtf8("url"))
        self.gridLayout_2.addWidget(self.url, 0, 14, 1, 1)
        self.Trabajo.addLayout(self.gridLayout_2, 0, 0, 1, 5)
        self.visor = QtGui.QGridLayout()
        self.visor.setObjectName(_fromUtf8("visor"))
        self.vistaHtml = QtWebKit.QWebView(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vistaHtml.sizePolicy().hasHeightForWidth())
        self.vistaHtml.setSizePolicy(sizePolicy)
        self.vistaHtml.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.vistaHtml.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vistaHtml.setProperty("url", QtCore.QUrl(_fromUtf8("file://pepe.html")))
        self.vistaHtml.setObjectName(_fromUtf8("vistaHtml"))
        self.visor.addWidget(self.vistaHtml, 2, 0, 1, 1)
        self.herramientasVisor_2 = QtGui.QHBoxLayout()
        self.herramientasVisor_2.setObjectName(_fromUtf8("herramientasVisor_2"))
        self.back = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.back.sizePolicy().hasHeightForWidth())
        self.back.setSizePolicy(sizePolicy)
        self.back.setMinimumSize(QtCore.QSize(32, 32))
        self.back.setMaximumSize(QtCore.QSize(32, 32))
        self.back.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.back.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.back.setText(_fromUtf8(""))
        icon32 = QtGui.QIcon()
        icon32.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/atras.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.back.setIcon(icon32)
        self.back.setAutoDefault(False)
        self.back.setDefault(False)
        self.back.setFlat(True)
        self.back.setObjectName(_fromUtf8("back"))
        self.herramientasVisor_2.addWidget(self.back)
        self.home = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.home.sizePolicy().hasHeightForWidth())
        self.home.setSizePolicy(sizePolicy)
        self.home.setMinimumSize(QtCore.QSize(32, 32))
        self.home.setMaximumSize(QtCore.QSize(32, 32))
        self.home.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.home.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.home.setText(_fromUtf8(""))
        icon33 = QtGui.QIcon()
        icon33.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/home.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.home.setIcon(icon33)
        self.home.setFlat(True)
        self.home.setObjectName(_fromUtf8("home"))
        self.herramientasVisor_2.addWidget(self.home)
        self.next = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.next.sizePolicy().hasHeightForWidth())
        self.next.setSizePolicy(sizePolicy)
        self.next.setMinimumSize(QtCore.QSize(32, 32))
        self.next.setMaximumSize(QtCore.QSize(32, 32))
        self.next.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.next.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.next.setText(_fromUtf8(""))
        icon34 = QtGui.QIcon()
        icon34.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/Siguiente.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.next.setIcon(icon34)
        self.next.setFlat(True)
        self.next.setObjectName(_fromUtf8("next"))
        self.herramientasVisor_2.addWidget(self.next)
        self.buscador = QtGui.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.buscador.setFont(font)
        self.buscador.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.buscador.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.buscador.setAutoFillBackground(False)
        self.buscador.setText(_fromUtf8(""))
        self.buscador.setFrame(True)
        self.buscador.setEchoMode(QtGui.QLineEdit.Normal)
        self.buscador.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.buscador.setDragEnabled(False)
        self.buscador.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.buscador.setObjectName(_fromUtf8("buscador"))
        self.herramientasVisor_2.addWidget(self.buscador)
        self.ir = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ir.sizePolicy().hasHeightForWidth())
        self.ir.setSizePolicy(sizePolicy)
        self.ir.setMinimumSize(QtCore.QSize(32, 32))
        self.ir.setMaximumSize(QtCore.QSize(32, 32))
        self.ir.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ir.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.ir.setAutoFillBackground(False)
        self.ir.setText(_fromUtf8(""))
        icon35 = QtGui.QIcon()
        icon35.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/go.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ir.setIcon(icon35)
        self.ir.setFlat(True)
        self.ir.setObjectName(_fromUtf8("ir"))
        self.herramientasVisor_2.addWidget(self.ir)
        self.imagenes = QtGui.QCheckBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imagenes.sizePolicy().hasHeightForWidth())
        self.imagenes.setSizePolicy(sizePolicy)
        self.imagenes.setMinimumSize(QtCore.QSize(94, 32))
        self.imagenes.setMaximumSize(QtCore.QSize(94, 32))
        self.imagenes.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.imagenes.setAutoFillBackground(False)
        self.imagenes.setCheckable(True)
        self.imagenes.setChecked(True)
        self.imagenes.setAutoRepeat(False)
        self.imagenes.setAutoRepeatDelay(0)
        self.imagenes.setAutoRepeatInterval(0)
        self.imagenes.setTristate(False)
        self.imagenes.setObjectName(_fromUtf8("imagenes"))
        self.herramientasVisor_2.addWidget(self.imagenes)
        self.visor.addLayout(self.herramientasVisor_2, 0, 0, 1, 1)
        self.Trabajo.addLayout(self.visor, 1, 4, 1, 1)
        Editor2.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(Editor2)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 774, 27))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuPepe = QtGui.QMenu(self.menubar)
        self.menuPepe.setObjectName(_fromUtf8("menuPepe"))
        self.menuEditar = QtGui.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Nimbus Sans L"))
        self.menuEditar.setFont(font)
        self.menuEditar.setObjectName(_fromUtf8("menuEditar"))
        self.menuLinea = QtGui.QMenu(self.menuEditar)
        icon36 = QtGui.QIcon()
        icon36.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/lineaF.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuLinea.setIcon(icon36)
        self.menuLinea.setObjectName(_fromUtf8("menuLinea"))
        self.menuFormato = QtGui.QMenu(self.menuEditar)
        icon37 = QtGui.QIcon()
        icon37.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/formato.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuFormato.setIcon(icon37)
        self.menuFormato.setObjectName(_fromUtf8("menuFormato"))
        self.menuInsertar = QtGui.QMenu(self.menubar)
        self.menuInsertar.setObjectName(_fromUtf8("menuInsertar"))
        self.menuExportar = QtGui.QMenu(self.menubar)
        self.menuExportar.setObjectName(_fromUtf8("menuExportar"))
        self.menuComunes = QtGui.QMenu(self.menuExportar)
        icon38 = QtGui.QIcon()
        icon38.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/convertirComunes.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuComunes.setIcon(icon38)
        self.menuComunes.setObjectName(_fromUtf8("menuComunes"))
        self.menuOtros = QtGui.QMenu(self.menuExportar)
        icon39 = QtGui.QIcon()
        icon39.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/convertirOtros.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuOtros.setIcon(icon39)
        self.menuOtros.setObjectName(_fromUtf8("menuOtros"))
        Editor2.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(Editor2)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        Editor2.setStatusBar(self.statusbar)
        self.actionArchivo = QtGui.QAction(Editor2)
        icon40 = QtGui.QIcon()
        icon40.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/Nuevo.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionArchivo.setIcon(icon40)
        self.actionArchivo.setSoftKeyRole(QtGui.QAction.NoSoftKey)
        self.actionArchivo.setIconVisibleInMenu(False)
        self.actionArchivo.setObjectName(_fromUtf8("actionArchivo"))
        self.actionAbrir = QtGui.QAction(Editor2)
        icon41 = QtGui.QIcon()
        icon41.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/abrir.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionAbrir.setIcon(icon41)
        self.actionAbrir.setObjectName(_fromUtf8("actionAbrir"))
        self.actionGuardar = QtGui.QAction(Editor2)
        icon42 = QtGui.QIcon()
        icon42.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/Guardar.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionGuardar.setIcon(icon42)
        self.actionGuardar.setObjectName(_fromUtf8("actionGuardar"))
        self.actionImprimir = QtGui.QAction(Editor2)
        self.actionImprimir.setObjectName(_fromUtf8("actionImprimir"))
        self.actionCerrar = QtGui.QAction(Editor2)
        icon43 = QtGui.QIcon()
        icon43.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/Salir.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionCerrar.setIcon(icon43)
        self.actionCerrar.setObjectName(_fromUtf8("actionCerrar"))
        self.actionTitulo = QtGui.QAction(Editor2)
        icon44 = QtGui.QIcon()
        icon44.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/Titulo.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionTitulo.setIcon(icon44)
        self.actionTitulo.setObjectName(_fromUtf8("actionTitulo"))
        self.actionCita = QtGui.QAction(Editor2)
        self.actionCita.setIcon(icon21)
        self.actionCita.setObjectName(_fromUtf8("actionCita"))
        self.actionCodigo = QtGui.QAction(Editor2)
        self.actionCodigo.setIcon(icon22)
        self.actionCodigo.setObjectName(_fromUtf8("actionCodigo"))
        self.actionLista_Numerica = QtGui.QAction(Editor2)
        self.actionLista_Numerica.setIcon(icon23)
        self.actionLista_Numerica.setObjectName(_fromUtf8("actionLista_Numerica"))
        self.actionLista = QtGui.QAction(Editor2)
        self.actionLista.setIcon(icon24)
        self.actionLista.setObjectName(_fromUtf8("actionLista"))
        self.actionSeparador_linea = QtGui.QAction(Editor2)
        self.actionSeparador_linea.setIcon(icon4)
        self.actionSeparador_linea.setObjectName(_fromUtf8("actionSeparador_linea"))
        self.actionNegrita = QtGui.QAction(Editor2)
        self.actionNegrita.setIcon(icon5)
        self.actionNegrita.setObjectName(_fromUtf8("actionNegrita"))
        self.actionCursiva = QtGui.QAction(Editor2)
        self.actionCursiva.setIcon(icon6)
        self.actionCursiva.setObjectName(_fromUtf8("actionCursiva"))
        self.actionInsertar_Contenido = QtGui.QAction(Editor2)
        icon45 = QtGui.QIcon()
        icon45.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/imagen.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionInsertar_Contenido.setIcon(icon45)
        self.actionInsertar_Contenido.setObjectName(_fromUtf8("actionInsertar_Contenido"))
        self.actionInsertar_Utilidad = QtGui.QAction(Editor2)
        icon46 = QtGui.QIcon()
        icon46.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/utilidad.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionInsertar_Utilidad.setIcon(icon46)
        self.actionInsertar_Utilidad.setObjectName(_fromUtf8("actionInsertar_Utilidad"))
        self.actionDeshacer = QtGui.QAction(Editor2)
        icon47 = QtGui.QIcon()
        icon47.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/deshacer.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionDeshacer.setIcon(icon47)
        self.actionDeshacer.setObjectName(_fromUtf8("actionDeshacer"))
        self.actionRehacer = QtGui.QAction(Editor2)
        icon48 = QtGui.QIcon()
        icon48.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/rehacer.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionRehacer.setIcon(icon48)
        self.actionRehacer.setObjectName(_fromUtf8("actionRehacer"))
        self.actionSeleccionar_todo = QtGui.QAction(Editor2)
        self.actionSeleccionar_todo.setObjectName(_fromUtf8("actionSeleccionar_todo"))
        self.actionCopiar = QtGui.QAction(Editor2)
        icon49 = QtGui.QIcon()
        icon49.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/copiar.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionCopiar.setIcon(icon49)
        self.actionCopiar.setObjectName(_fromUtf8("actionCopiar"))
        self.actionCortar = QtGui.QAction(Editor2)
        icon50 = QtGui.QIcon()
        icon50.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/cortar.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionCortar.setIcon(icon50)
        self.actionCortar.setObjectName(_fromUtf8("actionCortar"))
        self.actionPegar = QtGui.QAction(Editor2)
        icon51 = QtGui.QIcon()
        icon51.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/pegar.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionPegar.setIcon(icon51)
        self.actionPegar.setObjectName(_fromUtf8("actionPegar"))
        self.actionGuardar_Como = QtGui.QAction(Editor2)
        self.actionGuardar_Como.setIcon(icon25)
        self.actionGuardar_Como.setObjectName(_fromUtf8("actionGuardar_Como"))
        self.actionCerra = QtGui.QAction(Editor2)
        icon52 = QtGui.QIcon()
        icon52.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/Salir.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCerra.setIcon(icon52)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("TeX Gyre Pagella"))
        self.actionCerra.setFont(font)
        self.actionCerra.setObjectName(_fromUtf8("actionCerra"))
        self.action_odt = QtGui.QAction(Editor2)
        self.action_odt.setObjectName(_fromUtf8("action_odt"))
        self.action_docx = QtGui.QAction(Editor2)
        self.action_docx.setObjectName(_fromUtf8("action_docx"))
        self.action_json = QtGui.QAction(Editor2)
        self.action_json.setObjectName(_fromUtf8("action_json"))
        self.action_epub = QtGui.QAction(Editor2)
        self.action_epub.setObjectName(_fromUtf8("action_epub"))
        self.action_epub3 = QtGui.QAction(Editor2)
        self.action_epub3.setObjectName(_fromUtf8("action_epub3"))
        self.action_fb2 = QtGui.QAction(Editor2)
        self.action_fb2.setObjectName(_fromUtf8("action_fb2"))
        self.action_s6 = QtGui.QAction(Editor2)
        self.action_s6.setObjectName(_fromUtf8("action_s6"))
        self.action_slidy = QtGui.QAction(Editor2)
        self.action_slidy.setObjectName(_fromUtf8("action_slidy"))
        self.action_slideus = QtGui.QAction(Editor2)
        self.action_slideus.setObjectName(_fromUtf8("action_slideus"))
        self.action_dzslides = QtGui.QAction(Editor2)
        self.action_dzslides.setObjectName(_fromUtf8("action_dzslides"))
        self.action_docbook = QtGui.QAction(Editor2)
        self.action_docbook.setObjectName(_fromUtf8("action_docbook"))
        self.action_tex = QtGui.QAction(Editor2)
        self.action_tex.setObjectName(_fromUtf8("action_tex"))
        self.action_txt = QtGui.QAction(Editor2)
        self.action_txt.setObjectName(_fromUtf8("action_txt"))
        self.action_rst = QtGui.QAction(Editor2)
        self.action_rst.setObjectName(_fromUtf8("action_rst"))
        self.action_mediawiki = QtGui.QAction(Editor2)
        self.action_mediawiki.setObjectName(_fromUtf8("action_mediawiki"))
        self.action_textile = QtGui.QAction(Editor2)
        self.action_textile.setObjectName(_fromUtf8("action_textile"))
        self.action_rtf = QtGui.QAction(Editor2)
        self.action_rtf.setObjectName(_fromUtf8("action_rtf"))
        self.action_org = QtGui.QAction(Editor2)
        self.action_org.setObjectName(_fromUtf8("action_org"))
        self.action_asciioc = QtGui.QAction(Editor2)
        self.action_asciioc.setObjectName(_fromUtf8("action_asciioc"))
        self.action_native = QtGui.QAction(Editor2)
        self.action_native.setObjectName(_fromUtf8("action_native"))
        self.actionOdt = QtGui.QAction(Editor2)
        self.actionOdt.setObjectName(_fromUtf8("actionOdt"))
        self.actionDocx = QtGui.QAction(Editor2)
        self.actionDocx.setObjectName(_fromUtf8("actionDocx"))
        self.actionEpub = QtGui.QAction(Editor2)
        self.actionEpub.setObjectName(_fromUtf8("actionEpub"))
        self.actionEpub3 = QtGui.QAction(Editor2)
        self.actionEpub3.setObjectName(_fromUtf8("actionEpub3"))
        self.actionLatex = QtGui.QAction(Editor2)
        self.actionLatex.setObjectName(_fromUtf8("actionLatex"))
        self.actionPlain = QtGui.QAction(Editor2)
        self.actionPlain.setObjectName(_fromUtf8("actionPlain"))
        self.actionNative = QtGui.QAction(Editor2)
        self.actionNative.setObjectName(_fromUtf8("actionNative"))
        self.actionJson = QtGui.QAction(Editor2)
        self.actionJson.setObjectName(_fromUtf8("actionJson"))
        self.actionOpendocument = QtGui.QAction(Editor2)
        self.actionOpendocument.setObjectName(_fromUtf8("actionOpendocument"))
        self.actionBeamer = QtGui.QAction(Editor2)
        self.actionBeamer.setObjectName(_fromUtf8("actionBeamer"))
        self.actionContext = QtGui.QAction(Editor2)
        self.actionContext.setObjectName(_fromUtf8("actionContext"))
        self.actionTexinfo = QtGui.QAction(Editor2)
        self.actionTexinfo.setObjectName(_fromUtf8("actionTexinfo"))
        self.actionPlain_2 = QtGui.QAction(Editor2)
        self.actionPlain_2.setObjectName(_fromUtf8("actionPlain_2"))
        self.actionMediawiki = QtGui.QAction(Editor2)
        self.actionMediawiki.setObjectName(_fromUtf8("actionMediawiki"))
        self.actionS5 = QtGui.QAction(Editor2)
        self.actionS5.setObjectName(_fromUtf8("actionS5"))
        self.actionMan = QtGui.QAction(Editor2)
        self.actionMan.setObjectName(_fromUtf8("actionMan"))
        self.actionDocbook = QtGui.QAction(Editor2)
        self.actionDocbook.setObjectName(_fromUtf8("actionDocbook"))
        self.actionSlidy = QtGui.QAction(Editor2)
        self.actionSlidy.setObjectName(_fromUtf8("actionSlidy"))
        self.actionSlideous = QtGui.QAction(Editor2)
        self.actionSlideous.setObjectName(_fromUtf8("actionSlideous"))
        self.actionDzslides = QtGui.QAction(Editor2)
        self.actionDzslides.setObjectName(_fromUtf8("actionDzslides"))
        self.actionRtf = QtGui.QAction(Editor2)
        self.actionRtf.setObjectName(_fromUtf8("actionRtf"))
        self.actionOrg = QtGui.QAction(Editor2)
        self.actionOrg.setObjectName(_fromUtf8("actionOrg"))
        self.actionAsciidoc = QtGui.QAction(Editor2)
        self.actionAsciidoc.setObjectName(_fromUtf8("actionAsciidoc"))
        self.actionRst = QtGui.QAction(Editor2)
        self.actionRst.setObjectName(_fromUtf8("actionRst"))
        self.actionOpciones = QtGui.QAction(Editor2)
        icon53 = QtGui.QIcon()
        icon53.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/opciones.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionOpciones.setIcon(icon53)
        self.actionOpciones.setObjectName(_fromUtf8("actionOpciones"))
        self.action1_Titulo = QtGui.QAction(Editor2)
        self.action1_Titulo.setObjectName(_fromUtf8("action1_Titulo"))
        self.action2_Titulo = QtGui.QAction(Editor2)
        self.action2_Titulo.setObjectName(_fromUtf8("action2_Titulo"))
        self.action3_Titulo = QtGui.QAction(Editor2)
        self.action3_Titulo.setObjectName(_fromUtf8("action3_Titulo"))
        self.action1_Cita = QtGui.QAction(Editor2)
        self.action1_Cita.setObjectName(_fromUtf8("action1_Cita"))
        self.action2_Cita = QtGui.QAction(Editor2)
        self.action2_Cita.setObjectName(_fromUtf8("action2_Cita"))
        self.action3_Cita = QtGui.QAction(Editor2)
        self.action3_Cita.setObjectName(_fromUtf8("action3_Cita"))
        self.actionCodigo_2 = QtGui.QAction(Editor2)
        self.actionCodigo_2.setObjectName(_fromUtf8("actionCodigo_2"))
        self.actionLista_N = QtGui.QAction(Editor2)
        self.actionLista_N.setObjectName(_fromUtf8("actionLista_N"))
        self.actionLista_2 = QtGui.QAction(Editor2)
        self.actionLista_2.setObjectName(_fromUtf8("actionLista_2"))
        self.actionLinea_Divisora = QtGui.QAction(Editor2)
        self.actionLinea_Divisora.setObjectName(_fromUtf8("actionLinea_Divisora"))
        self.actionNegrita_2 = QtGui.QAction(Editor2)
        self.actionNegrita_2.setObjectName(_fromUtf8("actionNegrita_2"))
        self.actionCursiva_2 = QtGui.QAction(Editor2)
        self.actionCursiva_2.setObjectName(_fromUtf8("actionCursiva_2"))
        self.actionSubrayado = QtGui.QAction(Editor2)
        self.actionSubrayado.setObjectName(_fromUtf8("actionSubrayado"))
        self.actionTachado = QtGui.QAction(Editor2)
        self.actionTachado.setObjectName(_fromUtf8("actionTachado"))
        self.actionTexto_Mayor = QtGui.QAction(Editor2)
        self.actionTexto_Mayor.setObjectName(_fromUtf8("actionTexto_Mayor"))
        self.actionTexto_Menor = QtGui.QAction(Editor2)
        self.actionTexto_Menor.setObjectName(_fromUtf8("actionTexto_Menor"))
        self.actionSuperindice = QtGui.QAction(Editor2)
        self.actionSuperindice.setObjectName(_fromUtf8("actionSuperindice"))
        self.actionSubindice = QtGui.QAction(Editor2)
        self.actionSubindice.setObjectName(_fromUtf8("actionSubindice"))
        self.actionSalto_de_Linea = QtGui.QAction(Editor2)
        self.actionSalto_de_Linea.setObjectName(_fromUtf8("actionSalto_de_Linea"))
        self.actionParrafo_a_la_Izquierda = QtGui.QAction(Editor2)
        self.actionParrafo_a_la_Izquierda.setObjectName(_fromUtf8("actionParrafo_a_la_Izquierda"))
        self.actionParrafo_a_la_Derecha = QtGui.QAction(Editor2)
        self.actionParrafo_a_la_Derecha.setObjectName(_fromUtf8("actionParrafo_a_la_Derecha"))
        self.actionParrafo_Centrado = QtGui.QAction(Editor2)
        self.actionParrafo_Centrado.setObjectName(_fromUtf8("actionParrafo_Centrado"))
        self.actionRestaurar_Sesion = QtGui.QAction(Editor2)
        icon54 = QtGui.QIcon()
        icon54.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/restaurarSesion.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRestaurar_Sesion.setIcon(icon54)
        self.actionRestaurar_Sesion.setObjectName(_fromUtf8("actionRestaurar_Sesion"))
        self.actionPdf = QtGui.QAction(Editor2)
        self.actionPdf.setObjectName(_fromUtf8("actionPdf"))
        self.menuPepe.addAction(self.actionArchivo)
        self.menuPepe.addAction(self.actionAbrir)
        self.menuPepe.addAction(self.actionRestaurar_Sesion)
        self.menuPepe.addSeparator()
        self.menuPepe.addAction(self.actionGuardar)
        self.menuPepe.addAction(self.actionGuardar_Como)
        self.menuPepe.addSeparator()
        self.menuPepe.addAction(self.actionCerra)
        self.menuLinea.addAction(self.action1_Titulo)
        self.menuLinea.addAction(self.action1_Cita)
        self.menuLinea.addAction(self.actionCodigo_2)
        self.menuLinea.addAction(self.actionLista_N)
        self.menuLinea.addAction(self.actionLista_2)
        self.menuFormato.addAction(self.actionLinea_Divisora)
        self.menuFormato.addAction(self.actionNegrita_2)
        self.menuFormato.addAction(self.actionCursiva_2)
        self.menuFormato.addAction(self.actionSubrayado)
        self.menuFormato.addAction(self.actionTachado)
        self.menuFormato.addAction(self.actionTexto_Mayor)
        self.menuFormato.addAction(self.actionTexto_Menor)
        self.menuFormato.addAction(self.actionSuperindice)
        self.menuFormato.addAction(self.actionSubindice)
        self.menuFormato.addAction(self.actionSalto_de_Linea)
        self.menuFormato.addAction(self.actionParrafo_a_la_Izquierda)
        self.menuFormato.addAction(self.actionParrafo_a_la_Derecha)
        self.menuFormato.addAction(self.actionParrafo_Centrado)
        self.menuEditar.addAction(self.actionDeshacer)
        self.menuEditar.addAction(self.actionRehacer)
        self.menuEditar.addAction(self.actionCopiar)
        self.menuEditar.addAction(self.actionCortar)
        self.menuEditar.addAction(self.actionPegar)
        self.menuEditar.addSeparator()
        self.menuEditar.addAction(self.actionOpciones)
        self.menuEditar.addSeparator()
        self.menuEditar.addAction(self.menuLinea.menuAction())
        self.menuEditar.addAction(self.menuFormato.menuAction())
        self.menuInsertar.addAction(self.actionInsertar_Contenido)
        self.menuInsertar.addAction(self.actionInsertar_Utilidad)
        self.menuComunes.addAction(self.actionPdf)
        self.menuComunes.addAction(self.actionOdt)
        self.menuComunes.addAction(self.actionDocx)
        self.menuComunes.addAction(self.actionEpub)
        self.menuComunes.addAction(self.actionEpub3)
        self.menuComunes.addAction(self.actionLatex)
        self.menuComunes.addAction(self.actionPlain)
        self.menuComunes.addAction(self.actionS5)
        self.menuComunes.addAction(self.actionMan)
        self.menuComunes.addAction(self.actionRst)
        self.menuOtros.addAction(self.actionNative)
        self.menuOtros.addAction(self.actionJson)
        self.menuOtros.addAction(self.actionOpendocument)
        self.menuOtros.addAction(self.actionBeamer)
        self.menuOtros.addAction(self.actionContext)
        self.menuOtros.addAction(self.actionTexinfo)
        self.menuOtros.addAction(self.actionMediawiki)
        self.menuOtros.addAction(self.actionDocbook)
        self.menuOtros.addAction(self.actionSlidy)
        self.menuOtros.addAction(self.actionSlideous)
        self.menuOtros.addAction(self.actionDzslides)
        self.menuOtros.addAction(self.actionRtf)
        self.menuOtros.addAction(self.actionOrg)
        self.menuOtros.addAction(self.actionAsciidoc)
        self.menuExportar.addAction(self.menuComunes.menuAction())
        self.menuExportar.addAction(self.menuOtros.menuAction())
        self.menubar.addAction(self.menuPepe.menuAction())
        self.menubar.addAction(self.menuExportar.menuAction())
        self.menubar.addAction(self.menuEditar.menuAction())
        self.menubar.addAction(self.menuInsertar.menuAction())

        self.retranslateUi(Editor2)
        self.tabs.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionAbrir, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.abrirArchivo)
        QtCore.QObject.connect(self.actionGuardar, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.guardar)
        QtCore.QObject.connect(self.actionArchivo, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.nuevo)
        QtCore.QObject.connect(self.actionGuardar_Como, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.guardarEn)
        QtCore.QObject.connect(self.actionCerrar, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.close)
        QtCore.QObject.connect(self.actionCerra, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.close)
        QtCore.QObject.connect(self.actionOdt, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.odt)
        QtCore.QObject.connect(self.actionDocx, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.docx)
        QtCore.QObject.connect(self.actionEpub, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.epub)
        QtCore.QObject.connect(self.actionEpub3, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.epub3)
        QtCore.QObject.connect(self.actionLatex, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.latex)
        QtCore.QObject.connect(self.actionPlain, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.plain)
        QtCore.QObject.connect(self.actionS5, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.s5)
        QtCore.QObject.connect(self.actionMan, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.man)
        QtCore.QObject.connect(self.actionRst, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.rst)
        QtCore.QObject.connect(self.actionNative, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.native)
        QtCore.QObject.connect(self.actionJson, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.json)
        QtCore.QObject.connect(self.actionOpendocument, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.opendocument)
        QtCore.QObject.connect(self.actionBeamer, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.beamer)
        QtCore.QObject.connect(self.actionContext, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.context)
        QtCore.QObject.connect(self.actionTexinfo, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.texinfo)
        QtCore.QObject.connect(self.actionMediawiki, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.mediawiki)
        QtCore.QObject.connect(self.actionDocbook, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.docbook)
        QtCore.QObject.connect(self.actionSlidy, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.slidy)
        QtCore.QObject.connect(self.actionSlideous, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.slideous)
        QtCore.QObject.connect(self.actionDzslides, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.dzslides)
        QtCore.QObject.connect(self.actionRtf, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.rtf)
        QtCore.QObject.connect(self.actionOrg, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.org)
        QtCore.QObject.connect(self.actionAsciidoc, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.asciidoc)
        QtCore.QObject.connect(self.actionOpciones, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.opciones)
        QtCore.QObject.connect(self.seleccionFormato, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), Editor2.seleccionFormato)
        QtCore.QObject.connect(self.seleccionLinea, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), Editor2.seleccionLinea)
        QtCore.QObject.connect(self.guardar, QtCore.SIGNAL(_fromUtf8("clicked()")), Editor2.guardar)
        QtCore.QObject.connect(self.link, QtCore.SIGNAL(_fromUtf8("clicked()")), Editor2.link)
        QtCore.QObject.connect(self.html, QtCore.SIGNAL(_fromUtf8("clicked()")), Editor2.insUtilidad)
        QtCore.QObject.connect(self.aPdf, QtCore.SIGNAL(_fromUtf8("clicked()")), Editor2.aPdf)
        QtCore.QObject.connect(self.aOdt, QtCore.SIGNAL(_fromUtf8("clicked()")), Editor2.aOdt)
        QtCore.QObject.connect(self.aHtml, QtCore.SIGNAL(_fromUtf8("clicked()")), Editor2.aHtml)
        QtCore.QObject.connect(self.aEpub, QtCore.SIGNAL(_fromUtf8("clicked()")), Editor2.aEpub)
        QtCore.QObject.connect(self.action1_Titulo, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.titulo)
        QtCore.QObject.connect(self.action1_Cita, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.cita)
        QtCore.QObject.connect(self.actionLista_N, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.listaN)
        QtCore.QObject.connect(self.actionLista_2, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.lista)
        QtCore.QObject.connect(self.actionCodigo_2, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.codigo)
        QtCore.QObject.connect(self.actionLinea_Divisora, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.linea)
        QtCore.QObject.connect(self.actionNegrita_2, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.negrita)
        QtCore.QObject.connect(self.actionCursiva_2, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.cursiva)
        QtCore.QObject.connect(self.actionSubrayado, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.subrayado)
        QtCore.QObject.connect(self.actionTachado, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.tachado)
        QtCore.QObject.connect(self.actionTexto_Mayor, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.big)
        QtCore.QObject.connect(self.actionTexto_Menor, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.small)
        QtCore.QObject.connect(self.actionSuperindice, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.supind)
        QtCore.QObject.connect(self.actionSubindice, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.subind)
        QtCore.QObject.connect(self.actionSalto_de_Linea, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.saltoDeLinea)
        QtCore.QObject.connect(self.actionParrafo_a_la_Izquierda, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.parrIzq)
        QtCore.QObject.connect(self.actionParrafo_a_la_Derecha, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.parrDer)
        QtCore.QObject.connect(self.actionParrafo_Centrado, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.parrCen)
        QtCore.QObject.connect(self.back, QtCore.SIGNAL(_fromUtf8("clicked()")), Editor2.back)
        QtCore.QObject.connect(self.home, QtCore.SIGNAL(_fromUtf8("clicked()")), Editor2.home)
        QtCore.QObject.connect(self.next, QtCore.SIGNAL(_fromUtf8("clicked()")), Editor2.next)
        QtCore.QObject.connect(self.ir, QtCore.SIGNAL(_fromUtf8("clicked()")), Editor2.buscarG)
        QtCore.QObject.connect(self.editando, QtCore.SIGNAL(_fromUtf8("textChanged()")), Editor2.cambia)
        QtCore.QObject.connect(self.actionRestaurar_Sesion, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.restaurar)
        QtCore.QObject.connect(self.vistaHtml, QtCore.SIGNAL(_fromUtf8("loadStarted()")), Editor2.click)
        QtCore.QObject.connect(self.editando, QtCore.SIGNAL(_fromUtf8("textChanged()")), Editor2.estaModificado)
        QtCore.QObject.connect(self.actionInsertar_Contenido, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.link)
        QtCore.QObject.connect(self.actionInsertar_Utilidad, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.insUtilidad)
        QtCore.QObject.connect(self.actionPdf, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.aPdf)
        QtCore.QMetaObject.connectSlotsByName(Editor2)
        Editor2.setTabOrder(self.tabs, self.vistaHtml1)

    def retranslateUi(self, Editor2):
        Editor2.setWindowTitle(_translate("Editor2", "MarkYoun!", None))
        self.editando.setHtml(_translate("Editor2", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Nimbus Sans L\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.tabs.setTabText(self.tabs.indexOf(self.editor), _translate("Editor2", "Editor", None))
        self.tabs.setTabText(self.tabs.indexOf(self.vistapreliminar), _translate("Editor2", "Ayudame a entender esto Youn!", None))
        self.seleccionFormato.setToolTip(_translate("Editor2", "Formato general", None))
        self.seleccionFormato.setItemText(0, _translate("Editor2", "Formato", None))
        self.seleccionFormato.setItemText(1, _translate("Editor2", "Linea Divisora", None))
        self.seleccionFormato.setItemText(2, _translate("Editor2", "Negrita", None))
        self.seleccionFormato.setItemText(3, _translate("Editor2", "Cursiva", None))
        self.seleccionFormato.setItemText(4, _translate("Editor2", "Subrayado", None))
        self.seleccionFormato.setItemText(5, _translate("Editor2", "Tachado", None))
        self.seleccionFormato.setItemText(6, _translate("Editor2", "Texto Mayor", None))
        self.seleccionFormato.setItemText(7, _translate("Editor2", "Texto Menor", None))
        self.seleccionFormato.setItemText(8, _translate("Editor2", "Superindice", None))
        self.seleccionFormato.setItemText(9, _translate("Editor2", "Subindice", None))
        self.seleccionFormato.setItemText(10, _translate("Editor2", "Salto de Linea", None))
        self.seleccionFormato.setItemText(11, _translate("Editor2", "Parrafo a la Izquierda", None))
        self.seleccionFormato.setItemText(12, _translate("Editor2", "Parrafo a la Derecha", None))
        self.seleccionFormato.setItemText(13, _translate("Editor2", "Parrafo Centrado", None))
        self.seleccionLinea.setToolTip(_translate("Editor2", "Formato de Línea", None))
        self.seleccionLinea.setItemText(0, _translate("Editor2", "Linea", None))
        self.seleccionLinea.setItemText(1, _translate("Editor2", "1- Titulo", None))
        self.seleccionLinea.setItemText(2, _translate("Editor2", "2- Titulo", None))
        self.seleccionLinea.setItemText(3, _translate("Editor2", "3- Titulo", None))
        self.seleccionLinea.setItemText(4, _translate("Editor2", "1- Cita", None))
        self.seleccionLinea.setItemText(5, _translate("Editor2", "2- Cita", None))
        self.seleccionLinea.setItemText(6, _translate("Editor2", "3- Cita", None))
        self.seleccionLinea.setItemText(7, _translate("Editor2", "Codigo", None))
        self.seleccionLinea.setItemText(8, _translate("Editor2", "Lista N", None))
        self.seleccionLinea.setItemText(9, _translate("Editor2", "Lista", None))
        self.guardar.setToolTip(_translate("Editor2", "Guardar", None))
        self.html.setToolTip(_translate("Editor2", "Insertar Utilidades MarkYoun", None))
        self.link.setToolTip(_translate("Editor2", "Insertar Contenido Externo", None))
        self.aPdf.setToolTip(_translate("Editor2", "Exportar a pdf", None))
        self.aOdt.setToolTip(_translate("Editor2", "Exportar a odt", None))
        self.aEpub.setToolTip(_translate("Editor2", "Exportar a epub", None))
        self.aHtml.setToolTip(_translate("Editor2", "Exportar a Html", None))
        self.url.setPlaceholderText(_translate("Editor2", "Dirección del contenido", None))
        self.back.setToolTip(_translate("Editor2", "Anterior", None))
        self.home.setToolTip(_translate("Editor2", "Volver al visor", None))
        self.next.setToolTip(_translate("Editor2", "Siguiente", None))
        self.buscador.setToolTip(_translate("Editor2", "Buscar en Google", None))
        self.buscador.setPlaceholderText(_translate("Editor2", "Buscar", None))
        self.ir.setToolTip(_translate("Editor2", "Buscar", None))
        self.ir.setShortcut(_translate("Editor2", "Return", None))
        self.imagenes.setToolTip(_translate("Editor2", "Buscar solo imagenes?", None))
        self.imagenes.setText(_translate("Editor2", "Imagenes", None))
        self.menuPepe.setTitle(_translate("Editor2", "Archivo", None))
        self.menuEditar.setTitle(_translate("Editor2", "Edicion", None))
        self.menuLinea.setTitle(_translate("Editor2", "Linea", None))
        self.menuFormato.setTitle(_translate("Editor2", "Formato", None))
        self.menuInsertar.setTitle(_translate("Editor2", "Insertar", None))
        self.menuExportar.setTitle(_translate("Editor2", "Exportar A", None))
        self.menuComunes.setTitle(_translate("Editor2", "Comunes", None))
        self.menuOtros.setTitle(_translate("Editor2", "Otros", None))
        self.actionArchivo.setText(_translate("Editor2", "Nuevo", None))
        self.actionArchivo.setShortcut(_translate("Editor2", "Ctrl+N", None))
        self.actionAbrir.setText(_translate("Editor2", "Abrir", None))
        self.actionAbrir.setShortcut(_translate("Editor2", "Ctrl+O", None))
        self.actionGuardar.setText(_translate("Editor2", "Guardar", None))
        self.actionGuardar.setShortcut(_translate("Editor2", "Ctrl+S", None))
        self.actionImprimir.setText(_translate("Editor2", "Imprimir", None))
        self.actionCerrar.setText(_translate("Editor2", "Cerrar", None))
        self.actionCerrar.setShortcut(_translate("Editor2", "Ctrl+W", None))
        self.actionTitulo.setText(_translate("Editor2", "Titulo", None))
        self.actionTitulo.setShortcut(_translate("Editor2", "Ctrl+T", None))
        self.actionCita.setText(_translate("Editor2", "Cita", None))
        self.actionCita.setShortcut(_translate("Editor2", "Ctrl+Y", None))
        self.actionCodigo.setText(_translate("Editor2", "Codigo", None))
        self.actionCodigo.setShortcut(_translate("Editor2", "Ctrl+U", None))
        self.actionLista_Numerica.setText(_translate("Editor2", "Lista Numerica", None))
        self.actionLista_Numerica.setShortcut(_translate("Editor2", "Ctrl+K", None))
        self.actionLista.setText(_translate("Editor2", "Lista", None))
        self.actionLista.setShortcut(_translate("Editor2", "Ctrl+L", None))
        self.actionSeparador_linea.setText(_translate("Editor2", "Separador-linea", None))
        self.actionSeparador_linea.setShortcut(_translate("Editor2", "Ctrl+H", None))
        self.actionNegrita.setText(_translate("Editor2", "Negrita", None))
        self.actionNegrita.setShortcut(_translate("Editor2", "Ctrl+B", None))
        self.actionCursiva.setText(_translate("Editor2", "Cursiva", None))
        self.actionCursiva.setShortcut(_translate("Editor2", "Ctrl+I", None))
        self.actionInsertar_Contenido.setText(_translate("Editor2", "Insertar Contenido", None))
        self.actionInsertar_Contenido.setShortcut(_translate("Editor2", "Ctrl+Q", None))
        self.actionInsertar_Utilidad.setText(_translate("Editor2", "Insertar Utilidad", None))
        self.actionInsertar_Utilidad.setShortcut(_translate("Editor2", "Ctrl+E", None))
        self.actionDeshacer.setText(_translate("Editor2", "Deshacer", None))
        self.actionDeshacer.setShortcut(_translate("Editor2", "Ctrl+Z", None))
        self.actionRehacer.setText(_translate("Editor2", "Rehacer", None))
        self.actionSeleccionar_todo.setText(_translate("Editor2", "Seleccionar todo", None))
        self.actionCopiar.setText(_translate("Editor2", "Copiar", None))
        self.actionCopiar.setShortcut(_translate("Editor2", "Ctrl+C", None))
        self.actionCortar.setText(_translate("Editor2", "Cortar", None))
        self.actionCortar.setShortcut(_translate("Editor2", "Ctrl+X", None))
        self.actionPegar.setText(_translate("Editor2", "Pegar", None))
        self.actionPegar.setShortcut(_translate("Editor2", "Ctrl+V", None))
        self.actionGuardar_Como.setText(_translate("Editor2", "Guardar Como", None))
        self.actionGuardar_Como.setShortcut(_translate("Editor2", "Ctrl+G", None))
        self.actionCerra.setText(_translate("Editor2", "Cerrar", None))
        self.actionCerra.setShortcut(_translate("Editor2", "Ctrl+W", None))
        self.action_odt.setText(_translate("Editor2", "Comunes", None))
        self.action_docx.setText(_translate("Editor2", ".docx", None))
        self.action_json.setText(_translate("Editor2", ".json", None))
        self.action_epub.setText(_translate("Editor2", ".epub", None))
        self.action_epub3.setText(_translate("Editor2", ".epub3", None))
        self.action_fb2.setText(_translate("Editor2", ".fb2", None))
        self.action_s6.setText(_translate("Editor2", ".s5", None))
        self.action_slidy.setText(_translate("Editor2", ".slidy", None))
        self.action_slideus.setText(_translate("Editor2", ".slideus", None))
        self.action_dzslides.setText(_translate("Editor2", ".dzslides", None))
        self.action_docbook.setText(_translate("Editor2", ".docbook", None))
        self.action_tex.setText(_translate("Editor2", ".latex", None))
        self.action_txt.setText(_translate("Editor2", ".plain", None))
        self.action_rst.setText(_translate("Editor2", ".rst", None))
        self.action_mediawiki.setText(_translate("Editor2", ".mediawiki", None))
        self.action_textile.setText(_translate("Editor2", ".textile", None))
        self.action_rtf.setText(_translate("Editor2", ".rtf", None))
        self.action_org.setText(_translate("Editor2", ".org", None))
        self.action_asciioc.setText(_translate("Editor2", ".asciioc", None))
        self.action_native.setText(_translate("Editor2", ".native", None))
        self.actionOdt.setText(_translate("Editor2", "odt", None))
        self.actionDocx.setText(_translate("Editor2", "docx", None))
        self.actionEpub.setText(_translate("Editor2", "epub", None))
        self.actionEpub3.setText(_translate("Editor2", "epub3", None))
        self.actionLatex.setText(_translate("Editor2", "latex", None))
        self.actionPlain.setText(_translate("Editor2", "plain", None))
        self.actionNative.setText(_translate("Editor2", "native", None))
        self.actionJson.setText(_translate("Editor2", "json", None))
        self.actionOpendocument.setText(_translate("Editor2", "opendocument", None))
        self.actionBeamer.setText(_translate("Editor2", "beamer", None))
        self.actionContext.setText(_translate("Editor2", "context", None))
        self.actionTexinfo.setText(_translate("Editor2", "texinfo", None))
        self.actionPlain_2.setText(_translate("Editor2", "plain", None))
        self.actionMediawiki.setText(_translate("Editor2", "mediawiki", None))
        self.actionS5.setText(_translate("Editor2", "s5", None))
        self.actionMan.setText(_translate("Editor2", "man", None))
        self.actionDocbook.setText(_translate("Editor2", "docbook", None))
        self.actionSlidy.setText(_translate("Editor2", "slidy", None))
        self.actionSlideous.setText(_translate("Editor2", "slideous", None))
        self.actionDzslides.setText(_translate("Editor2", "dzslides", None))
        self.actionRtf.setText(_translate("Editor2", "rtf", None))
        self.actionOrg.setText(_translate("Editor2", "org", None))
        self.actionAsciidoc.setText(_translate("Editor2", "asciidoc", None))
        self.actionRst.setText(_translate("Editor2", "rst", None))
        self.actionOpciones.setText(_translate("Editor2", "Opciones", None))
        self.action1_Titulo.setText(_translate("Editor2", "Titulo", None))
        self.action1_Titulo.setShortcut(_translate("Editor2", "Ctrl+T", None))
        self.action2_Titulo.setText(_translate("Editor2", "2- Titulo", None))
        self.action3_Titulo.setText(_translate("Editor2", "3- Titulo", None))
        self.action1_Cita.setText(_translate("Editor2", "Cita", None))
        self.action1_Cita.setShortcut(_translate("Editor2", "Ctrl+Y", None))
        self.action2_Cita.setText(_translate("Editor2", "2- Cita", None))
        self.action3_Cita.setText(_translate("Editor2", "3- Cita", None))
        self.actionCodigo_2.setText(_translate("Editor2", "Codigo", None))
        self.actionCodigo_2.setShortcut(_translate("Editor2", "Ctrl+P", None))
        self.actionLista_N.setText(_translate("Editor2", "Lista N", None))
        self.actionLista_N.setShortcut(_translate("Editor2", "Ctrl+K", None))
        self.actionLista_2.setText(_translate("Editor2", "Lista", None))
        self.actionLista_2.setShortcut(_translate("Editor2", "Ctrl+L", None))
        self.actionLinea_Divisora.setText(_translate("Editor2", "Linea Divisora", None))
        self.actionLinea_Divisora.setShortcut(_translate("Editor2", "Ctrl+H", None))
        self.actionNegrita_2.setText(_translate("Editor2", "Negrita", None))
        self.actionNegrita_2.setShortcut(_translate("Editor2", "Ctrl+B", None))
        self.actionCursiva_2.setText(_translate("Editor2", "Cursiva", None))
        self.actionCursiva_2.setShortcut(_translate("Editor2", "Ctrl+I", None))
        self.actionSubrayado.setText(_translate("Editor2", "Subrayado", None))
        self.actionSubrayado.setShortcut(_translate("Editor2", "Ctrl+U", None))
        self.actionTachado.setText(_translate("Editor2", "Tachado", None))
        self.actionTachado.setShortcut(_translate("Editor2", "Ctrl+D", None))
        self.actionTexto_Mayor.setText(_translate("Editor2", "Texto Mayor", None))
        self.actionTexto_Mayor.setShortcut(_translate("Editor2", "Ctrl+J", None))
        self.actionTexto_Menor.setText(_translate("Editor2", "Texto Menor", None))
        self.actionTexto_Menor.setShortcut(_translate("Editor2", "Ctrl+M", None))
        self.actionSuperindice.setText(_translate("Editor2", "Superindice", None))
        self.actionSuperindice.setShortcut(_translate("Editor2", "Ctrl+Shift+Q", None))
        self.actionSubindice.setText(_translate("Editor2", "Subindice", None))
        self.actionSubindice.setShortcut(_translate("Editor2", "Ctrl+Shift+A", None))
        self.actionSalto_de_Linea.setText(_translate("Editor2", "Salto de Linea", None))
        self.actionSalto_de_Linea.setShortcut(_translate("Editor2", "Ctrl+Space", None))
        self.actionParrafo_a_la_Izquierda.setText(_translate("Editor2", "Parrafo a la Izquierda", None))
        self.actionParrafo_a_la_Izquierda.setShortcut(_translate("Editor2", "Ctrl+Shift+L", None))
        self.actionParrafo_a_la_Derecha.setText(_translate("Editor2", "Parrafo a la Derecha", None))
        self.actionParrafo_a_la_Derecha.setShortcut(_translate("Editor2", "Ctrl+Shift+R", None))
        self.actionParrafo_Centrado.setText(_translate("Editor2", "Parrafo Centrado", None))
        self.actionParrafo_Centrado.setShortcut(_translate("Editor2", "Ctrl+Shift+C", None))
        self.actionRestaurar_Sesion.setText(_translate("Editor2", "Restaurar Sesión", None))
        self.actionPdf.setText(_translate("Editor2", "pdf", None))

from PyQt4 import QtWebKit
