# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Editor.ui'
#
# Created: Mon May 12 20:22:39 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Editor(object):
    def setupUi(self, Editor):
        Editor.setObjectName(_fromUtf8("Editor"))
        Editor.resize(774, 466)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Nimbus Sans L"))
        Editor.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/icono.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Editor.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(Editor)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.Trabajo = QtGui.QGridLayout(self.centralwidget)
        self.Trabajo.setContentsMargins(-1, -1, -1, 9)
        self.Trabajo.setHorizontalSpacing(6)
        self.Trabajo.setVerticalSpacing(0)
        self.Trabajo.setObjectName(_fromUtf8("Trabajo"))
        self.tabs = QtGui.QTabWidget(self.centralwidget)
        self.tabs.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tabs.setDocumentMode(True)
        self.tabs.setMovable(True)
        self.tabs.setObjectName(_fromUtf8("tabs"))
        self.editor = QtGui.QWidget()
        self.editor.setObjectName(_fromUtf8("editor"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.editor)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.editando = QtGui.QTextEdit(self.editor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editando.sizePolicy().hasHeightForWidth())
        self.editando.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Nimbus Sans L"))
        self.editando.setFont(font)
        self.editando.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.editando.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.editando.setFrameShape(QtGui.QFrame.HLine)
        self.editando.setFrameShadow(QtGui.QFrame.Sunken)
        self.editando.setTabStopWidth(32)
        self.editando.setAcceptRichText(False)
        self.editando.setObjectName(_fromUtf8("editando"))
        self.horizontalLayout.addWidget(self.editando)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/archivo.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tabs.addTab(self.editor, icon1, _fromUtf8(""))
        self.vistapreliminar = QtGui.QWidget()
        self.vistapreliminar.setObjectName(_fromUtf8("vistapreliminar"))
        self.gridLayout_3 = QtGui.QGridLayout(self.vistapreliminar)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.vistaHtml1 = QtWebKit.QWebView(self.vistapreliminar)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Nimbus Sans L"))
        self.vistaHtml1.setFont(font)
        self.vistaHtml1.setProperty("url", QtCore.QUrl(_fromUtf8("file:///home/mateo/Escritorio/MarkYoun! v0.4 beta/Help/Ayuda.md.html")))
        self.vistaHtml1.setObjectName(_fromUtf8("vistaHtml1"))
        self.gridLayout_3.addWidget(self.vistaHtml1, 0, 0, 1, 1)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/Ayuda.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tabs.addTab(self.vistapreliminar, icon2, _fromUtf8(""))
        self.Trabajo.addWidget(self.tabs, 0, 0, 1, 1)
        self.visor = QtGui.QGridLayout()
        self.visor.setObjectName(_fromUtf8("visor"))
        self.vistaHtml = QtWebKit.QWebView(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vistaHtml.sizePolicy().hasHeightForWidth())
        self.vistaHtml.setSizePolicy(sizePolicy)
        self.vistaHtml.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.vistaHtml.setProperty("url", QtCore.QUrl(_fromUtf8("file://pepe.html")))
        self.vistaHtml.setObjectName(_fromUtf8("vistaHtml"))
        self.visor.addWidget(self.vistaHtml, 1, 0, 1, 1)
        self.Trabajo.addLayout(self.visor, 0, 1, 1, 1)
        Editor.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(Editor)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 774, 27))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuPepe = QtGui.QMenu(self.menubar)
        self.menuPepe.setObjectName(_fromUtf8("menuPepe"))
        self.menuEditar = QtGui.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Nimbus Sans L"))
        self.menuEditar.setFont(font)
        self.menuEditar.setObjectName(_fromUtf8("menuEditar"))
        self.menuLinea = QtGui.QMenu(self.menuEditar)
        self.menuLinea.setObjectName(_fromUtf8("menuLinea"))
        self.menuFormato = QtGui.QMenu(self.menuEditar)
        self.menuFormato.setObjectName(_fromUtf8("menuFormato"))
        self.menuInsertar = QtGui.QMenu(self.menubar)
        self.menuInsertar.setObjectName(_fromUtf8("menuInsertar"))
        self.menuExportar = QtGui.QMenu(self.menubar)
        self.menuExportar.setObjectName(_fromUtf8("menuExportar"))
        self.menuComunes = QtGui.QMenu(self.menuExportar)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/convertirComunes.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuComunes.setIcon(icon3)
        self.menuComunes.setObjectName(_fromUtf8("menuComunes"))
        self.menuOtros = QtGui.QMenu(self.menuExportar)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/convertirOtros.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuOtros.setIcon(icon4)
        self.menuOtros.setObjectName(_fromUtf8("menuOtros"))
        Editor.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(Editor)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        Editor.setStatusBar(self.statusbar)
        self.actionArchivo = QtGui.QAction(Editor)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/Nuevo.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionArchivo.setIcon(icon5)
        self.actionArchivo.setSoftKeyRole(QtGui.QAction.NoSoftKey)
        self.actionArchivo.setIconVisibleInMenu(False)
        self.actionArchivo.setObjectName(_fromUtf8("actionArchivo"))
        self.actionAbrir = QtGui.QAction(Editor)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/abrir.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionAbrir.setIcon(icon6)
        self.actionAbrir.setObjectName(_fromUtf8("actionAbrir"))
        self.actionGuardar = QtGui.QAction(Editor)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/Guardar.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionGuardar.setIcon(icon7)
        self.actionGuardar.setObjectName(_fromUtf8("actionGuardar"))
        self.actionImprimir = QtGui.QAction(Editor)
        self.actionImprimir.setObjectName(_fromUtf8("actionImprimir"))
        self.actionCerrar = QtGui.QAction(Editor)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/Salir.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionCerrar.setIcon(icon8)
        self.actionCerrar.setObjectName(_fromUtf8("actionCerrar"))
        self.actionTitulo = QtGui.QAction(Editor)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/Titulo.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionTitulo.setIcon(icon9)
        self.actionTitulo.setObjectName(_fromUtf8("actionTitulo"))
        self.actionCita = QtGui.QAction(Editor)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/cita.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionCita.setIcon(icon10)
        self.actionCita.setObjectName(_fromUtf8("actionCita"))
        self.actionCodigo = QtGui.QAction(Editor)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/codigo.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionCodigo.setIcon(icon11)
        self.actionCodigo.setObjectName(_fromUtf8("actionCodigo"))
        self.actionLista_Numerica = QtGui.QAction(Editor)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/listaN.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionLista_Numerica.setIcon(icon12)
        self.actionLista_Numerica.setObjectName(_fromUtf8("actionLista_Numerica"))
        self.actionLista = QtGui.QAction(Editor)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/lista.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionLista.setIcon(icon13)
        self.actionLista.setObjectName(_fromUtf8("actionLista"))
        self.actionSeparador_linea = QtGui.QAction(Editor)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/linea.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionSeparador_linea.setIcon(icon14)
        self.actionSeparador_linea.setObjectName(_fromUtf8("actionSeparador_linea"))
        self.actionNegrita = QtGui.QAction(Editor)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/Negrita.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionNegrita.setIcon(icon15)
        self.actionNegrita.setObjectName(_fromUtf8("actionNegrita"))
        self.actionCursiva = QtGui.QAction(Editor)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/Cursiva.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionCursiva.setIcon(icon16)
        self.actionCursiva.setObjectName(_fromUtf8("actionCursiva"))
        self.actionInsertar_Contenido = QtGui.QAction(Editor)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/imagen.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionInsertar_Contenido.setIcon(icon17)
        self.actionInsertar_Contenido.setObjectName(_fromUtf8("actionInsertar_Contenido"))
        self.actionInsertar_Utilidad = QtGui.QAction(Editor)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/utilidad.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionInsertar_Utilidad.setIcon(icon18)
        self.actionInsertar_Utilidad.setObjectName(_fromUtf8("actionInsertar_Utilidad"))
        self.actionDeshacer = QtGui.QAction(Editor)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/deshacer.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionDeshacer.setIcon(icon19)
        self.actionDeshacer.setObjectName(_fromUtf8("actionDeshacer"))
        self.actionRehacer = QtGui.QAction(Editor)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/rehacer.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionRehacer.setIcon(icon20)
        self.actionRehacer.setObjectName(_fromUtf8("actionRehacer"))
        self.actionSeleccionar_todo = QtGui.QAction(Editor)
        self.actionSeleccionar_todo.setObjectName(_fromUtf8("actionSeleccionar_todo"))
        self.actionCopiar = QtGui.QAction(Editor)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/copiar.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionCopiar.setIcon(icon21)
        self.actionCopiar.setObjectName(_fromUtf8("actionCopiar"))
        self.actionCortar = QtGui.QAction(Editor)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/cortar.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionCortar.setIcon(icon22)
        self.actionCortar.setObjectName(_fromUtf8("actionCortar"))
        self.actionPegar = QtGui.QAction(Editor)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/pegar.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionPegar.setIcon(icon23)
        self.actionPegar.setObjectName(_fromUtf8("actionPegar"))
        self.actionGuardar_Como = QtGui.QAction(Editor)
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/Guardar.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGuardar_Como.setIcon(icon24)
        self.actionGuardar_Como.setObjectName(_fromUtf8("actionGuardar_Como"))
        self.actionCerra = QtGui.QAction(Editor)
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/Salir.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCerra.setIcon(icon25)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("TeX Gyre Pagella"))
        self.actionCerra.setFont(font)
        self.actionCerra.setObjectName(_fromUtf8("actionCerra"))
        self.action_odt = QtGui.QAction(Editor)
        self.action_odt.setObjectName(_fromUtf8("action_odt"))
        self.action_docx = QtGui.QAction(Editor)
        self.action_docx.setObjectName(_fromUtf8("action_docx"))
        self.action_json = QtGui.QAction(Editor)
        self.action_json.setObjectName(_fromUtf8("action_json"))
        self.action_epub = QtGui.QAction(Editor)
        self.action_epub.setObjectName(_fromUtf8("action_epub"))
        self.action_epub3 = QtGui.QAction(Editor)
        self.action_epub3.setObjectName(_fromUtf8("action_epub3"))
        self.action_fb2 = QtGui.QAction(Editor)
        self.action_fb2.setObjectName(_fromUtf8("action_fb2"))
        self.action_s6 = QtGui.QAction(Editor)
        self.action_s6.setObjectName(_fromUtf8("action_s6"))
        self.action_slidy = QtGui.QAction(Editor)
        self.action_slidy.setObjectName(_fromUtf8("action_slidy"))
        self.action_slideus = QtGui.QAction(Editor)
        self.action_slideus.setObjectName(_fromUtf8("action_slideus"))
        self.action_dzslides = QtGui.QAction(Editor)
        self.action_dzslides.setObjectName(_fromUtf8("action_dzslides"))
        self.action_docbook = QtGui.QAction(Editor)
        self.action_docbook.setObjectName(_fromUtf8("action_docbook"))
        self.action_tex = QtGui.QAction(Editor)
        self.action_tex.setObjectName(_fromUtf8("action_tex"))
        self.action_txt = QtGui.QAction(Editor)
        self.action_txt.setObjectName(_fromUtf8("action_txt"))
        self.action_rst = QtGui.QAction(Editor)
        self.action_rst.setObjectName(_fromUtf8("action_rst"))
        self.action_mediawiki = QtGui.QAction(Editor)
        self.action_mediawiki.setObjectName(_fromUtf8("action_mediawiki"))
        self.action_textile = QtGui.QAction(Editor)
        self.action_textile.setObjectName(_fromUtf8("action_textile"))
        self.action_rtf = QtGui.QAction(Editor)
        self.action_rtf.setObjectName(_fromUtf8("action_rtf"))
        self.action_org = QtGui.QAction(Editor)
        self.action_org.setObjectName(_fromUtf8("action_org"))
        self.action_asciioc = QtGui.QAction(Editor)
        self.action_asciioc.setObjectName(_fromUtf8("action_asciioc"))
        self.action_native = QtGui.QAction(Editor)
        self.action_native.setObjectName(_fromUtf8("action_native"))
        self.actionOdt = QtGui.QAction(Editor)
        self.actionOdt.setObjectName(_fromUtf8("actionOdt"))
        self.actionDocx = QtGui.QAction(Editor)
        self.actionDocx.setObjectName(_fromUtf8("actionDocx"))
        self.actionEpub = QtGui.QAction(Editor)
        self.actionEpub.setObjectName(_fromUtf8("actionEpub"))
        self.actionEpub3 = QtGui.QAction(Editor)
        self.actionEpub3.setObjectName(_fromUtf8("actionEpub3"))
        self.actionLatex = QtGui.QAction(Editor)
        self.actionLatex.setObjectName(_fromUtf8("actionLatex"))
        self.actionPlain = QtGui.QAction(Editor)
        self.actionPlain.setObjectName(_fromUtf8("actionPlain"))
        self.actionNative = QtGui.QAction(Editor)
        self.actionNative.setObjectName(_fromUtf8("actionNative"))
        self.actionJson = QtGui.QAction(Editor)
        self.actionJson.setObjectName(_fromUtf8("actionJson"))
        self.actionOpendocument = QtGui.QAction(Editor)
        self.actionOpendocument.setObjectName(_fromUtf8("actionOpendocument"))
        self.actionBeamer = QtGui.QAction(Editor)
        self.actionBeamer.setObjectName(_fromUtf8("actionBeamer"))
        self.actionContext = QtGui.QAction(Editor)
        self.actionContext.setObjectName(_fromUtf8("actionContext"))
        self.actionTexinfo = QtGui.QAction(Editor)
        self.actionTexinfo.setObjectName(_fromUtf8("actionTexinfo"))
        self.actionPlain_2 = QtGui.QAction(Editor)
        self.actionPlain_2.setObjectName(_fromUtf8("actionPlain_2"))
        self.actionMediawiki = QtGui.QAction(Editor)
        self.actionMediawiki.setObjectName(_fromUtf8("actionMediawiki"))
        self.actionS5 = QtGui.QAction(Editor)
        self.actionS5.setObjectName(_fromUtf8("actionS5"))
        self.actionMan = QtGui.QAction(Editor)
        self.actionMan.setObjectName(_fromUtf8("actionMan"))
        self.actionDocbook = QtGui.QAction(Editor)
        self.actionDocbook.setObjectName(_fromUtf8("actionDocbook"))
        self.actionSlidy = QtGui.QAction(Editor)
        self.actionSlidy.setObjectName(_fromUtf8("actionSlidy"))
        self.actionSlideous = QtGui.QAction(Editor)
        self.actionSlideous.setObjectName(_fromUtf8("actionSlideous"))
        self.actionDzslides = QtGui.QAction(Editor)
        self.actionDzslides.setObjectName(_fromUtf8("actionDzslides"))
        self.actionRtf = QtGui.QAction(Editor)
        self.actionRtf.setObjectName(_fromUtf8("actionRtf"))
        self.actionOrg = QtGui.QAction(Editor)
        self.actionOrg.setObjectName(_fromUtf8("actionOrg"))
        self.actionAsciidoc = QtGui.QAction(Editor)
        self.actionAsciidoc.setObjectName(_fromUtf8("actionAsciidoc"))
        self.actionRst = QtGui.QAction(Editor)
        self.actionRst.setObjectName(_fromUtf8("actionRst"))
        self.actionOpciones = QtGui.QAction(Editor)
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/opciones.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionOpciones.setIcon(icon26)
        self.actionOpciones.setObjectName(_fromUtf8("actionOpciones"))
        self.action1_Titulo = QtGui.QAction(Editor)
        self.action1_Titulo.setObjectName(_fromUtf8("action1_Titulo"))
        self.action2_Titulo = QtGui.QAction(Editor)
        self.action2_Titulo.setObjectName(_fromUtf8("action2_Titulo"))
        self.action3_Titulo = QtGui.QAction(Editor)
        self.action3_Titulo.setObjectName(_fromUtf8("action3_Titulo"))
        self.action1_Cita = QtGui.QAction(Editor)
        self.action1_Cita.setObjectName(_fromUtf8("action1_Cita"))
        self.action2_Cita = QtGui.QAction(Editor)
        self.action2_Cita.setObjectName(_fromUtf8("action2_Cita"))
        self.action3_Cita = QtGui.QAction(Editor)
        self.action3_Cita.setObjectName(_fromUtf8("action3_Cita"))
        self.actionCodigo_2 = QtGui.QAction(Editor)
        self.actionCodigo_2.setObjectName(_fromUtf8("actionCodigo_2"))
        self.actionLista_N = QtGui.QAction(Editor)
        self.actionLista_N.setObjectName(_fromUtf8("actionLista_N"))
        self.actionLista_2 = QtGui.QAction(Editor)
        self.actionLista_2.setObjectName(_fromUtf8("actionLista_2"))
        self.actionLinea_Divisora = QtGui.QAction(Editor)
        self.actionLinea_Divisora.setObjectName(_fromUtf8("actionLinea_Divisora"))
        self.actionNegrita_2 = QtGui.QAction(Editor)
        self.actionNegrita_2.setObjectName(_fromUtf8("actionNegrita_2"))
        self.actionCursiva_2 = QtGui.QAction(Editor)
        self.actionCursiva_2.setObjectName(_fromUtf8("actionCursiva_2"))
        self.actionSubrayado = QtGui.QAction(Editor)
        self.actionSubrayado.setObjectName(_fromUtf8("actionSubrayado"))
        self.actionTachado = QtGui.QAction(Editor)
        self.actionTachado.setObjectName(_fromUtf8("actionTachado"))
        self.actionTexto_Mayor = QtGui.QAction(Editor)
        self.actionTexto_Mayor.setObjectName(_fromUtf8("actionTexto_Mayor"))
        self.actionTexto_Menor = QtGui.QAction(Editor)
        self.actionTexto_Menor.setObjectName(_fromUtf8("actionTexto_Menor"))
        self.actionSuperindice = QtGui.QAction(Editor)
        self.actionSuperindice.setObjectName(_fromUtf8("actionSuperindice"))
        self.actionSubindice = QtGui.QAction(Editor)
        self.actionSubindice.setObjectName(_fromUtf8("actionSubindice"))
        self.actionSalto_de_Linea = QtGui.QAction(Editor)
        self.actionSalto_de_Linea.setObjectName(_fromUtf8("actionSalto_de_Linea"))
        self.actionParrafo_a_la_Izquierda = QtGui.QAction(Editor)
        self.actionParrafo_a_la_Izquierda.setObjectName(_fromUtf8("actionParrafo_a_la_Izquierda"))
        self.actionParrafo_a_la_Derecha = QtGui.QAction(Editor)
        self.actionParrafo_a_la_Derecha.setObjectName(_fromUtf8("actionParrafo_a_la_Derecha"))
        self.actionParrafo_Centrado = QtGui.QAction(Editor)
        self.actionParrafo_Centrado.setObjectName(_fromUtf8("actionParrafo_Centrado"))
        self.actionRestaurar_Sesion = QtGui.QAction(Editor)
        self.actionRestaurar_Sesion.setObjectName(_fromUtf8("actionRestaurar_Sesion"))
        self.menuPepe.addAction(self.actionArchivo)
        self.menuPepe.addAction(self.actionAbrir)
        self.menuPepe.addAction(self.actionRestaurar_Sesion)
        self.menuPepe.addSeparator()
        self.menuPepe.addAction(self.actionGuardar)
        self.menuPepe.addAction(self.actionGuardar_Como)
        self.menuPepe.addSeparator()
        self.menuPepe.addAction(self.actionCerra)
        self.menuLinea.addAction(self.action1_Titulo)
        self.menuLinea.addAction(self.action1_Cita)
        self.menuLinea.addAction(self.actionCodigo_2)
        self.menuLinea.addAction(self.actionLista_N)
        self.menuLinea.addAction(self.actionLista_2)
        self.menuFormato.addAction(self.actionLinea_Divisora)
        self.menuFormato.addAction(self.actionNegrita_2)
        self.menuFormato.addAction(self.actionCursiva_2)
        self.menuFormato.addAction(self.actionSubrayado)
        self.menuFormato.addAction(self.actionTachado)
        self.menuFormato.addAction(self.actionTexto_Mayor)
        self.menuFormato.addAction(self.actionTexto_Menor)
        self.menuFormato.addAction(self.actionSuperindice)
        self.menuFormato.addAction(self.actionSubindice)
        self.menuFormato.addAction(self.actionSalto_de_Linea)
        self.menuFormato.addAction(self.actionParrafo_a_la_Izquierda)
        self.menuFormato.addAction(self.actionParrafo_a_la_Derecha)
        self.menuFormato.addAction(self.actionParrafo_Centrado)
        self.menuEditar.addAction(self.actionDeshacer)
        self.menuEditar.addAction(self.actionRehacer)
        self.menuEditar.addAction(self.actionCopiar)
        self.menuEditar.addAction(self.actionCortar)
        self.menuEditar.addAction(self.actionPegar)
        self.menuEditar.addSeparator()
        self.menuEditar.addAction(self.actionOpciones)
        self.menuEditar.addSeparator()
        self.menuEditar.addAction(self.menuLinea.menuAction())
        self.menuEditar.addAction(self.menuFormato.menuAction())
        self.menuInsertar.addAction(self.actionInsertar_Contenido)
        self.menuInsertar.addAction(self.actionInsertar_Utilidad)
        self.menuComunes.addAction(self.actionOdt)
        self.menuComunes.addAction(self.actionDocx)
        self.menuComunes.addAction(self.actionEpub)
        self.menuComunes.addAction(self.actionEpub3)
        self.menuComunes.addAction(self.actionLatex)
        self.menuComunes.addAction(self.actionPlain)
        self.menuComunes.addAction(self.actionS5)
        self.menuComunes.addAction(self.actionMan)
        self.menuComunes.addAction(self.actionRst)
        self.menuOtros.addAction(self.actionNative)
        self.menuOtros.addAction(self.actionJson)
        self.menuOtros.addAction(self.actionOpendocument)
        self.menuOtros.addAction(self.actionBeamer)
        self.menuOtros.addAction(self.actionContext)
        self.menuOtros.addAction(self.actionTexinfo)
        self.menuOtros.addAction(self.actionMediawiki)
        self.menuOtros.addAction(self.actionDocbook)
        self.menuOtros.addAction(self.actionSlidy)
        self.menuOtros.addAction(self.actionSlideous)
        self.menuOtros.addAction(self.actionDzslides)
        self.menuOtros.addAction(self.actionRtf)
        self.menuOtros.addAction(self.actionOrg)
        self.menuOtros.addAction(self.actionAsciidoc)
        self.menuExportar.addAction(self.menuComunes.menuAction())
        self.menuExportar.addAction(self.menuOtros.menuAction())
        self.menubar.addAction(self.menuPepe.menuAction())
        self.menubar.addAction(self.menuExportar.menuAction())
        self.menubar.addAction(self.menuEditar.menuAction())
        self.menubar.addAction(self.menuInsertar.menuAction())

        self.retranslateUi(Editor)
        self.tabs.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionAbrir, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor.abrirArchivo)
        QtCore.QObject.connect(self.actionGuardar, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor.guardar)
        QtCore.QObject.connect(self.actionArchivo, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor.nuevo)
        QtCore.QObject.connect(self.actionGuardar_Como, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor.guardarEn)
        QtCore.QObject.connect(self.actionCerrar, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor.close)
        QtCore.QObject.connect(self.actionCerra, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor.close)
        QtCore.QObject.connect(self.actionOdt, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor.odt)
        QtCore.QObject.connect(self.actionDocx, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor.docx)
        QtCore.QObject.connect(self.actionEpub, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor.epub)
        QtCore.QObject.connect(self.actionEpub3, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor.epub3)
        QtCore.QObject.connect(self.actionLatex, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor.latex)
        QtCore.QObject.connect(self.actionPlain, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor.plain)
        QtCore.QObject.connect(self.actionS5, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor.s5)
        QtCore.QObject.connect(self.actionMan, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor.man)
        QtCore.QObject.connect(self.actionRst, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor.rst)
        QtCore.QObject.connect(self.actionNative, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor.native)
        QtCore.QObject.connect(self.actionJson, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor.json)
        QtCore.QObject.connect(self.actionOpendocument, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor.opendocument)
        QtCore.QObject.connect(self.actionBeamer, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor.beamer)
        QtCore.QObject.connect(self.actionContext, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor.context)
        QtCore.QObject.connect(self.actionTexinfo, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor.texinfo)
        QtCore.QObject.connect(self.actionMediawiki, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor.mediawiki)
        QtCore.QObject.connect(self.actionDocbook, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor.docbook)
        QtCore.QObject.connect(self.actionSlidy, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor.slidy)
        QtCore.QObject.connect(self.actionSlideous, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor.slideous)
        QtCore.QObject.connect(self.actionDzslides, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor.dzslides)
        QtCore.QObject.connect(self.actionRtf, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor.rtf)
        QtCore.QObject.connect(self.actionOrg, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor.org)
        QtCore.QObject.connect(self.actionAsciidoc, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor.asciidoc)
        QtCore.QObject.connect(self.actionOpciones, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor.opciones)
        QtCore.QObject.connect(self.action1_Titulo, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor.titulo)
        QtCore.QObject.connect(self.action1_Cita, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor.cita)
        QtCore.QObject.connect(self.actionLista_N, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor.listaN)
        QtCore.QObject.connect(self.actionLista_2, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor.lista)
        QtCore.QObject.connect(self.actionCodigo_2, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor.codigo)
        QtCore.QObject.connect(self.actionLinea_Divisora, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor.linea)
        QtCore.QObject.connect(self.actionNegrita_2, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor.negrita)
        QtCore.QObject.connect(self.actionCursiva_2, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor.cursiva)
        QtCore.QObject.connect(self.actionSubrayado, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor.subrayado)
        QtCore.QObject.connect(self.actionTachado, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor.tachado)
        QtCore.QObject.connect(self.actionTexto_Mayor, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor.big)
        QtCore.QObject.connect(self.actionTexto_Menor, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor.small)
        QtCore.QObject.connect(self.actionSuperindice, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor.supind)
        QtCore.QObject.connect(self.actionSubindice, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor.subind)
        QtCore.QObject.connect(self.actionSalto_de_Linea, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor.saltoDeLinea)
        QtCore.QObject.connect(self.actionParrafo_a_la_Izquierda, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor.parrIzq)
        QtCore.QObject.connect(self.actionParrafo_a_la_Derecha, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor.parrDer)
        QtCore.QObject.connect(self.actionParrafo_Centrado, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor.parrCen)
        QtCore.QObject.connect(self.editando, QtCore.SIGNAL(_fromUtf8("textChanged()")), Editor.cambia)
        QtCore.QObject.connect(self.actionRestaurar_Sesion, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor.restaurar)
        QtCore.QObject.connect(self.vistaHtml, QtCore.SIGNAL(_fromUtf8("loadStarted()")), Editor.click)
        QtCore.QObject.connect(self.editando, QtCore.SIGNAL(_fromUtf8("textChanged()")), Editor.estaModificado)
        QtCore.QMetaObject.connectSlotsByName(Editor)
        Editor.setTabOrder(self.tabs, self.vistaHtml1)

    def retranslateUi(self, Editor):
        Editor.setWindowTitle(_translate("Editor", "MarkYoun!", None))
        self.editando.setHtml(_translate("Editor", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Nimbus Sans L\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.tabs.setTabText(self.tabs.indexOf(self.editor), _translate("Editor", "Editor", None))
        self.tabs.setTabText(self.tabs.indexOf(self.vistapreliminar), _translate("Editor", "Ayudame a entender esto Youn!", None))
        self.menuPepe.setTitle(_translate("Editor", "Archivo", None))
        self.menuEditar.setTitle(_translate("Editor", "Edicion", None))
        self.menuLinea.setTitle(_translate("Editor", "Linea", None))
        self.menuFormato.setTitle(_translate("Editor", "Formato", None))
        self.menuInsertar.setTitle(_translate("Editor", "Insertar", None))
        self.menuExportar.setTitle(_translate("Editor", "Exportar A", None))
        self.menuComunes.setTitle(_translate("Editor", "Comunes", None))
        self.menuOtros.setTitle(_translate("Editor", "Otros", None))
        self.actionArchivo.setText(_translate("Editor", "Nuevo", None))
        self.actionArchivo.setShortcut(_translate("Editor", "Ctrl+N", None))
        self.actionAbrir.setText(_translate("Editor", "Abrir", None))
        self.actionAbrir.setShortcut(_translate("Editor", "Ctrl+O", None))
        self.actionGuardar.setText(_translate("Editor", "Guardar", None))
        self.actionGuardar.setShortcut(_translate("Editor", "Ctrl+S", None))
        self.actionImprimir.setText(_translate("Editor", "Imprimir", None))
        self.actionCerrar.setText(_translate("Editor", "Cerrar", None))
        self.actionCerrar.setShortcut(_translate("Editor", "Ctrl+W", None))
        self.actionTitulo.setText(_translate("Editor", "Titulo", None))
        self.actionTitulo.setShortcut(_translate("Editor", "Ctrl+T", None))
        self.actionCita.setText(_translate("Editor", "Cita", None))
        self.actionCita.setShortcut(_translate("Editor", "Ctrl+Y", None))
        self.actionCodigo.setText(_translate("Editor", "Codigo", None))
        self.actionCodigo.setShortcut(_translate("Editor", "Ctrl+U", None))
        self.actionLista_Numerica.setText(_translate("Editor", "Lista Numerica", None))
        self.actionLista_Numerica.setShortcut(_translate("Editor", "Ctrl+K", None))
        self.actionLista.setText(_translate("Editor", "Lista", None))
        self.actionLista.setShortcut(_translate("Editor", "Ctrl+L", None))
        self.actionSeparador_linea.setText(_translate("Editor", "Separador-linea", None))
        self.actionSeparador_linea.setShortcut(_translate("Editor", "Ctrl+H", None))
        self.actionNegrita.setText(_translate("Editor", "Negrita", None))
        self.actionNegrita.setShortcut(_translate("Editor", "Ctrl+B", None))
        self.actionCursiva.setText(_translate("Editor", "Cursiva", None))
        self.actionCursiva.setShortcut(_translate("Editor", "Ctrl+I", None))
        self.actionInsertar_Contenido.setText(_translate("Editor", "Insertar Contenido", None))
        self.actionInsertar_Contenido.setShortcut(_translate("Editor", "Ctrl+Q", None))
        self.actionInsertar_Utilidad.setText(_translate("Editor", "Insertar Utilidad", None))
        self.actionInsertar_Utilidad.setShortcut(_translate("Editor", "Ctrl+E", None))
        self.actionDeshacer.setText(_translate("Editor", "Deshacer", None))
        self.actionDeshacer.setShortcut(_translate("Editor", "Ctrl+Z", None))
        self.actionRehacer.setText(_translate("Editor", "Rehacer", None))
        self.actionSeleccionar_todo.setText(_translate("Editor", "Seleccionar todo", None))
        self.actionCopiar.setText(_translate("Editor", "Copiar", None))
        self.actionCopiar.setShortcut(_translate("Editor", "Ctrl+C", None))
        self.actionCortar.setText(_translate("Editor", "Cortar", None))
        self.actionCortar.setShortcut(_translate("Editor", "Ctrl+X", None))
        self.actionPegar.setText(_translate("Editor", "Pegar", None))
        self.actionPegar.setShortcut(_translate("Editor", "Ctrl+V", None))
        self.actionGuardar_Como.setText(_translate("Editor", "Guardar Como", None))
        self.actionGuardar_Como.setShortcut(_translate("Editor", "Ctrl+G", None))
        self.actionCerra.setText(_translate("Editor", "Cerrar", None))
        self.actionCerra.setShortcut(_translate("Editor", "Ctrl+W", None))
        self.action_odt.setText(_translate("Editor", "Comunes", None))
        self.action_docx.setText(_translate("Editor", ".docx", None))
        self.action_json.setText(_translate("Editor", ".json", None))
        self.action_epub.setText(_translate("Editor", ".epub", None))
        self.action_epub3.setText(_translate("Editor", ".epub3", None))
        self.action_fb2.setText(_translate("Editor", ".fb2", None))
        self.action_s6.setText(_translate("Editor", ".s5", None))
        self.action_slidy.setText(_translate("Editor", ".slidy", None))
        self.action_slideus.setText(_translate("Editor", ".slideus", None))
        self.action_dzslides.setText(_translate("Editor", ".dzslides", None))
        self.action_docbook.setText(_translate("Editor", ".docbook", None))
        self.action_tex.setText(_translate("Editor", ".latex", None))
        self.action_txt.setText(_translate("Editor", ".plain", None))
        self.action_rst.setText(_translate("Editor", ".rst", None))
        self.action_mediawiki.setText(_translate("Editor", ".mediawiki", None))
        self.action_textile.setText(_translate("Editor", ".textile", None))
        self.action_rtf.setText(_translate("Editor", ".rtf", None))
        self.action_org.setText(_translate("Editor", ".org", None))
        self.action_asciioc.setText(_translate("Editor", ".asciioc", None))
        self.action_native.setText(_translate("Editor", ".native", None))
        self.actionOdt.setText(_translate("Editor", "odt", None))
        self.actionDocx.setText(_translate("Editor", "docx", None))
        self.actionEpub.setText(_translate("Editor", "epub", None))
        self.actionEpub3.setText(_translate("Editor", "epub3", None))
        self.actionLatex.setText(_translate("Editor", "latex", None))
        self.actionPlain.setText(_translate("Editor", "plain", None))
        self.actionNative.setText(_translate("Editor", "native", None))
        self.actionJson.setText(_translate("Editor", "json", None))
        self.actionOpendocument.setText(_translate("Editor", "opendocument", None))
        self.actionBeamer.setText(_translate("Editor", "beamer", None))
        self.actionContext.setText(_translate("Editor", "context", None))
        self.actionTexinfo.setText(_translate("Editor", "texinfo", None))
        self.actionPlain_2.setText(_translate("Editor", "plain", None))
        self.actionMediawiki.setText(_translate("Editor", "mediawiki", None))
        self.actionS5.setText(_translate("Editor", "s5", None))
        self.actionMan.setText(_translate("Editor", "man", None))
        self.actionDocbook.setText(_translate("Editor", "docbook", None))
        self.actionSlidy.setText(_translate("Editor", "slidy", None))
        self.actionSlideous.setText(_translate("Editor", "slideous", None))
        self.actionDzslides.setText(_translate("Editor", "dzslides", None))
        self.actionRtf.setText(_translate("Editor", "rtf", None))
        self.actionOrg.setText(_translate("Editor", "org", None))
        self.actionAsciidoc.setText(_translate("Editor", "asciidoc", None))
        self.actionRst.setText(_translate("Editor", "rst", None))
        self.actionOpciones.setText(_translate("Editor", "Opciones", None))
        self.action1_Titulo.setText(_translate("Editor", "Titulo", None))
        self.action1_Titulo.setShortcut(_translate("Editor", "Ctrl+T", None))
        self.action2_Titulo.setText(_translate("Editor", "2- Titulo", None))
        self.action3_Titulo.setText(_translate("Editor", "3- Titulo", None))
        self.action1_Cita.setText(_translate("Editor", "Cita", None))
        self.action1_Cita.setShortcut(_translate("Editor", "Ctrl+Y", None))
        self.action2_Cita.setText(_translate("Editor", "2- Cita", None))
        self.action3_Cita.setText(_translate("Editor", "3- Cita", None))
        self.actionCodigo_2.setText(_translate("Editor", "Codigo", None))
        self.actionCodigo_2.setShortcut(_translate("Editor", "Ctrl+P", None))
        self.actionLista_N.setText(_translate("Editor", "Lista N", None))
        self.actionLista_N.setShortcut(_translate("Editor", "Ctrl+K", None))
        self.actionLista_2.setText(_translate("Editor", "Lista", None))
        self.actionLista_2.setShortcut(_translate("Editor", "Ctrl+L", None))
        self.actionLinea_Divisora.setText(_translate("Editor", "Linea Divisora", None))
        self.actionLinea_Divisora.setShortcut(_translate("Editor", "Ctrl+H", None))
        self.actionNegrita_2.setText(_translate("Editor", "Negrita", None))
        self.actionNegrita_2.setShortcut(_translate("Editor", "Ctrl+B", None))
        self.actionCursiva_2.setText(_translate("Editor", "Cursiva", None))
        self.actionCursiva_2.setShortcut(_translate("Editor", "Ctrl+I", None))
        self.actionSubrayado.setText(_translate("Editor", "Subrayado", None))
        self.actionSubrayado.setShortcut(_translate("Editor", "Ctrl+U", None))
        self.actionTachado.setText(_translate("Editor", "Tachado", None))
        self.actionTachado.setShortcut(_translate("Editor", "Ctrl+D", None))
        self.actionTexto_Mayor.setText(_translate("Editor", "Texto Mayor", None))
        self.actionTexto_Mayor.setShortcut(_translate("Editor", "Ctrl+J", None))
        self.actionTexto_Menor.setText(_translate("Editor", "Texto Menor", None))
        self.actionTexto_Menor.setShortcut(_translate("Editor", "Ctrl+M", None))
        self.actionSuperindice.setText(_translate("Editor", "Superindice", None))
        self.actionSuperindice.setShortcut(_translate("Editor", "Ctrl+Shift+Q", None))
        self.actionSubindice.setText(_translate("Editor", "Subindice", None))
        self.actionSubindice.setShortcut(_translate("Editor", "Ctrl+Shift+A", None))
        self.actionSalto_de_Linea.setText(_translate("Editor", "Salto de Linea", None))
        self.actionSalto_de_Linea.setShortcut(_translate("Editor", "Ctrl+Space", None))
        self.actionParrafo_a_la_Izquierda.setText(_translate("Editor", "Parrafo a la Izquierda", None))
        self.actionParrafo_a_la_Izquierda.setShortcut(_translate("Editor", "Ctrl+Shift+L", None))
        self.actionParrafo_a_la_Derecha.setText(_translate("Editor", "Parrafo a la Derecha", None))
        self.actionParrafo_a_la_Derecha.setShortcut(_translate("Editor", "Ctrl+Shift+R", None))
        self.actionParrafo_Centrado.setText(_translate("Editor", "Parrafo Centrado", None))
        self.actionParrafo_Centrado.setShortcut(_translate("Editor", "Ctrl+Shift+C", None))
        self.actionRestaurar_Sesion.setText(_translate("Editor", "Restaurar Sesión", None))

from PyQt4 import QtWebKit
