# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Editor2.ui'
#
# Created: Mon Apr 14 19:12:41 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Editor2(object):
    def setupUi(self, Editor2):
        Editor2.setObjectName(_fromUtf8("Editor2"))
        Editor2.resize(728, 491)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Nimbus Sans L"))
        Editor2.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/icono.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Editor2.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(Editor2)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.Trabajo = QtGui.QGridLayout(self.centralwidget)
        self.Trabajo.setSpacing(6)
        self.Trabajo.setContentsMargins(-1, -1, -1, 9)
        self.Trabajo.setObjectName(_fromUtf8("Trabajo"))
        self.vistaHtml = QtWebKit.QWebView(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vistaHtml.sizePolicy().hasHeightForWidth())
        self.vistaHtml.setSizePolicy(sizePolicy)
        self.vistaHtml.setFocusPolicy(QtCore.Qt.NoFocus)
        self.vistaHtml.setProperty("url", QtCore.QUrl(_fromUtf8("file:///home/mateo/Escritorio/proyecto/pepe.html")))
        self.vistaHtml.setObjectName(_fromUtf8("vistaHtml"))
        self.Trabajo.addWidget(self.vistaHtml, 3, 2, 1, 1)
        self.tabs = QtGui.QTabWidget(self.centralwidget)
        self.tabs.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tabs.setObjectName(_fromUtf8("tabs"))
        self.editor = QtGui.QWidget()
        self.editor.setObjectName(_fromUtf8("editor"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.editor)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.editando = QtGui.QTextEdit(self.editor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editando.sizePolicy().hasHeightForWidth())
        self.editando.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Nimbus Sans L"))
        self.editando.setFont(font)
        self.editando.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.editando.setFrameShape(QtGui.QFrame.HLine)
        self.editando.setFrameShadow(QtGui.QFrame.Sunken)
        self.editando.setTabStopWidth(40)
        self.editando.setObjectName(_fromUtf8("editando"))
        self.horizontalLayout.addWidget(self.editando)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/archivo.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tabs.addTab(self.editor, icon1, _fromUtf8(""))
        self.vistapreliminar = QtGui.QWidget()
        self.vistapreliminar.setObjectName(_fromUtf8("vistapreliminar"))
        self.gridLayout_3 = QtGui.QGridLayout(self.vistapreliminar)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.vistaHtml1 = QtWebKit.QWebView(self.vistapreliminar)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Nimbus Sans L"))
        self.vistaHtml1.setFont(font)
        self.vistaHtml1.setProperty("url", QtCore.QUrl(_fromUtf8("file:///home/mateo/Escritorio/MarkYoun! v0.4 beta/Help/Ayuda.md.html")))
        self.vistaHtml1.setObjectName(_fromUtf8("vistaHtml1"))
        self.gridLayout_3.addWidget(self.vistaHtml1, 0, 0, 1, 1)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/Ayuda.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tabs.addTab(self.vistapreliminar, icon2, _fromUtf8(""))
        self.Trabajo.addWidget(self.tabs, 3, 1, 1, 1)
        self.layoutHerramientas = QtGui.QHBoxLayout()
        self.layoutHerramientas.setSpacing(0)
        self.layoutHerramientas.setObjectName(_fromUtf8("layoutHerramientas"))
        self.seleccion = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.seleccion.sizePolicy().hasHeightForWidth())
        self.seleccion.setSizePolicy(sizePolicy)
        self.seleccion.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.seleccion.setFocusPolicy(QtCore.Qt.NoFocus)
        self.seleccion.setObjectName(_fromUtf8("seleccion"))
        self.seleccion.addItem(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/H1.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.seleccion.addItem(icon3, _fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/H2.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.seleccion.addItem(icon4, _fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/H3.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.seleccion.addItem(icon5, _fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/cita.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.seleccion.addItem(icon6, _fromUtf8(""))
        self.seleccion.addItem(icon6, _fromUtf8(""))
        self.seleccion.addItem(icon6, _fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/codigo.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.seleccion.addItem(icon7, _fromUtf8(""))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/listaN.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.seleccion.addItem(icon8, _fromUtf8(""))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/lista.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.seleccion.addItem(icon9, _fromUtf8(""))
        self.layoutHerramientas.addWidget(self.seleccion)
        self.guardar = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.guardar.sizePolicy().hasHeightForWidth())
        self.guardar.setSizePolicy(sizePolicy)
        self.guardar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.guardar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.guardar.setText(_fromUtf8(""))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/Guardar.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.guardar.setIcon(icon10)
        self.guardar.setIconSize(QtCore.QSize(32, 32))
        self.guardar.setAutoDefault(False)
        self.guardar.setDefault(False)
        self.guardar.setFlat(False)
        self.guardar.setObjectName(_fromUtf8("guardar"))
        self.layoutHerramientas.addWidget(self.guardar)
        self.link = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.link.sizePolicy().hasHeightForWidth())
        self.link.setSizePolicy(sizePolicy)
        self.link.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.link.setFocusPolicy(QtCore.Qt.NoFocus)
        self.link.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/imagen.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.link.setIcon(icon11)
        self.link.setIconSize(QtCore.QSize(32, 32))
        self.link.setFlat(False)
        self.link.setObjectName(_fromUtf8("link"))
        self.layoutHerramientas.addWidget(self.link)
        self.html = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.html.sizePolicy().hasHeightForWidth())
        self.html.setSizePolicy(sizePolicy)
        self.html.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.html.setFocusPolicy(QtCore.Qt.NoFocus)
        self.html.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/utilidad.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.html.setIcon(icon12)
        self.html.setIconSize(QtCore.QSize(32, 32))
        self.html.setFlat(False)
        self.html.setObjectName(_fromUtf8("html"))
        self.layoutHerramientas.addWidget(self.html)
        self.linea = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.linea.sizePolicy().hasHeightForWidth())
        self.linea.setSizePolicy(sizePolicy)
        self.linea.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.linea.setFocusPolicy(QtCore.Qt.NoFocus)
        self.linea.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/linea.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.linea.setIcon(icon13)
        self.linea.setIconSize(QtCore.QSize(32, 32))
        self.linea.setShortcut(_fromUtf8(""))
        self.linea.setAutoDefault(False)
        self.linea.setDefault(False)
        self.linea.setFlat(False)
        self.linea.setObjectName(_fromUtf8("linea"))
        self.layoutHerramientas.addWidget(self.linea)
        self.negrita = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.negrita.sizePolicy().hasHeightForWidth())
        self.negrita.setSizePolicy(sizePolicy)
        self.negrita.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.negrita.setFocusPolicy(QtCore.Qt.NoFocus)
        self.negrita.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/Negrita.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.negrita.setIcon(icon14)
        self.negrita.setIconSize(QtCore.QSize(32, 32))
        self.negrita.setShortcut(_fromUtf8(""))
        self.negrita.setAutoDefault(False)
        self.negrita.setDefault(False)
        self.negrita.setFlat(False)
        self.negrita.setObjectName(_fromUtf8("negrita"))
        self.layoutHerramientas.addWidget(self.negrita)
        self.cursiva = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cursiva.sizePolicy().hasHeightForWidth())
        self.cursiva.setSizePolicy(sizePolicy)
        self.cursiva.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cursiva.setFocusPolicy(QtCore.Qt.NoFocus)
        self.cursiva.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/Cursiva.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cursiva.setIcon(icon15)
        self.cursiva.setIconSize(QtCore.QSize(32, 32))
        self.cursiva.setShortcut(_fromUtf8(""))
        self.cursiva.setAutoDefault(False)
        self.cursiva.setDefault(False)
        self.cursiva.setFlat(False)
        self.cursiva.setObjectName(_fromUtf8("cursiva"))
        self.layoutHerramientas.addWidget(self.cursiva)
        self.Trabajo.addLayout(self.layoutHerramientas, 0, 0, 3, 3)
        Editor2.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(Editor2)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 728, 27))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuPepe = QtGui.QMenu(self.menubar)
        self.menuPepe.setObjectName(_fromUtf8("menuPepe"))
        self.menuEditar = QtGui.QMenu(self.menubar)
        self.menuEditar.setObjectName(_fromUtf8("menuEditar"))
        self.menuInsertar = QtGui.QMenu(self.menubar)
        self.menuInsertar.setObjectName(_fromUtf8("menuInsertar"))
        self.menuExportar = QtGui.QMenu(self.menubar)
        self.menuExportar.setObjectName(_fromUtf8("menuExportar"))
        self.menuComunes = QtGui.QMenu(self.menuExportar)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/convertirComunes.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuComunes.setIcon(icon16)
        self.menuComunes.setObjectName(_fromUtf8("menuComunes"))
        self.menuOtros = QtGui.QMenu(self.menuExportar)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/convertirOtros.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuOtros.setIcon(icon17)
        self.menuOtros.setObjectName(_fromUtf8("menuOtros"))
        Editor2.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(Editor2)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        Editor2.setStatusBar(self.statusbar)
        self.actionArchivo = QtGui.QAction(Editor2)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/Nuevo.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionArchivo.setIcon(icon18)
        self.actionArchivo.setSoftKeyRole(QtGui.QAction.NoSoftKey)
        self.actionArchivo.setIconVisibleInMenu(False)
        self.actionArchivo.setObjectName(_fromUtf8("actionArchivo"))
        self.actionAbrir = QtGui.QAction(Editor2)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/abrir.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionAbrir.setIcon(icon19)
        self.actionAbrir.setObjectName(_fromUtf8("actionAbrir"))
        self.actionGuardar = QtGui.QAction(Editor2)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/Guardar.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionGuardar.setIcon(icon20)
        self.actionGuardar.setObjectName(_fromUtf8("actionGuardar"))
        self.actionImprimir = QtGui.QAction(Editor2)
        self.actionImprimir.setObjectName(_fromUtf8("actionImprimir"))
        self.actionCerrar = QtGui.QAction(Editor2)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/Salir.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionCerrar.setIcon(icon21)
        self.actionCerrar.setObjectName(_fromUtf8("actionCerrar"))
        self.actionTitulo = QtGui.QAction(Editor2)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/Titulo.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionTitulo.setIcon(icon22)
        self.actionTitulo.setObjectName(_fromUtf8("actionTitulo"))
        self.actionCita = QtGui.QAction(Editor2)
        self.actionCita.setIcon(icon6)
        self.actionCita.setObjectName(_fromUtf8("actionCita"))
        self.actionCodigo = QtGui.QAction(Editor2)
        self.actionCodigo.setIcon(icon7)
        self.actionCodigo.setObjectName(_fromUtf8("actionCodigo"))
        self.actionLista_Numerica = QtGui.QAction(Editor2)
        self.actionLista_Numerica.setIcon(icon8)
        self.actionLista_Numerica.setObjectName(_fromUtf8("actionLista_Numerica"))
        self.actionLista = QtGui.QAction(Editor2)
        self.actionLista.setIcon(icon9)
        self.actionLista.setObjectName(_fromUtf8("actionLista"))
        self.actionSeparador_linea = QtGui.QAction(Editor2)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/linea.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionSeparador_linea.setIcon(icon23)
        self.actionSeparador_linea.setObjectName(_fromUtf8("actionSeparador_linea"))
        self.actionNegrita = QtGui.QAction(Editor2)
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/Negrita.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionNegrita.setIcon(icon24)
        self.actionNegrita.setObjectName(_fromUtf8("actionNegrita"))
        self.actionCursiva = QtGui.QAction(Editor2)
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/Cursiva.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionCursiva.setIcon(icon25)
        self.actionCursiva.setObjectName(_fromUtf8("actionCursiva"))
        self.actionInsertar_Contenido = QtGui.QAction(Editor2)
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/imagen.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionInsertar_Contenido.setIcon(icon26)
        self.actionInsertar_Contenido.setObjectName(_fromUtf8("actionInsertar_Contenido"))
        self.actionInsertar_Utilidad = QtGui.QAction(Editor2)
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/utilidad.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionInsertar_Utilidad.setIcon(icon27)
        self.actionInsertar_Utilidad.setObjectName(_fromUtf8("actionInsertar_Utilidad"))
        self.actionDeshacer = QtGui.QAction(Editor2)
        icon28 = QtGui.QIcon()
        icon28.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/deshacer.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionDeshacer.setIcon(icon28)
        self.actionDeshacer.setObjectName(_fromUtf8("actionDeshacer"))
        self.actionRehacer = QtGui.QAction(Editor2)
        icon29 = QtGui.QIcon()
        icon29.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/rehacer.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionRehacer.setIcon(icon29)
        self.actionRehacer.setObjectName(_fromUtf8("actionRehacer"))
        self.actionSeleccionar_todo = QtGui.QAction(Editor2)
        self.actionSeleccionar_todo.setObjectName(_fromUtf8("actionSeleccionar_todo"))
        self.actionCopiar = QtGui.QAction(Editor2)
        icon30 = QtGui.QIcon()
        icon30.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/copiar.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionCopiar.setIcon(icon30)
        self.actionCopiar.setObjectName(_fromUtf8("actionCopiar"))
        self.actionCortar = QtGui.QAction(Editor2)
        icon31 = QtGui.QIcon()
        icon31.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/cortar.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionCortar.setIcon(icon31)
        self.actionCortar.setObjectName(_fromUtf8("actionCortar"))
        self.actionPegar = QtGui.QAction(Editor2)
        icon32 = QtGui.QIcon()
        icon32.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/pegar.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionPegar.setIcon(icon32)
        self.actionPegar.setObjectName(_fromUtf8("actionPegar"))
        self.actionGuardar_Como = QtGui.QAction(Editor2)
        self.actionGuardar_Como.setIcon(icon10)
        self.actionGuardar_Como.setObjectName(_fromUtf8("actionGuardar_Como"))
        self.actionCerra = QtGui.QAction(Editor2)
        icon33 = QtGui.QIcon()
        icon33.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/Salir.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCerra.setIcon(icon33)
        self.actionCerra.setObjectName(_fromUtf8("actionCerra"))
        self.action_odt = QtGui.QAction(Editor2)
        self.action_odt.setObjectName(_fromUtf8("action_odt"))
        self.action_docx = QtGui.QAction(Editor2)
        self.action_docx.setObjectName(_fromUtf8("action_docx"))
        self.action_json = QtGui.QAction(Editor2)
        self.action_json.setObjectName(_fromUtf8("action_json"))
        self.action_epub = QtGui.QAction(Editor2)
        self.action_epub.setObjectName(_fromUtf8("action_epub"))
        self.action_epub3 = QtGui.QAction(Editor2)
        self.action_epub3.setObjectName(_fromUtf8("action_epub3"))
        self.action_fb2 = QtGui.QAction(Editor2)
        self.action_fb2.setObjectName(_fromUtf8("action_fb2"))
        self.action_s6 = QtGui.QAction(Editor2)
        self.action_s6.setObjectName(_fromUtf8("action_s6"))
        self.action_slidy = QtGui.QAction(Editor2)
        self.action_slidy.setObjectName(_fromUtf8("action_slidy"))
        self.action_slideus = QtGui.QAction(Editor2)
        self.action_slideus.setObjectName(_fromUtf8("action_slideus"))
        self.action_dzslides = QtGui.QAction(Editor2)
        self.action_dzslides.setObjectName(_fromUtf8("action_dzslides"))
        self.action_docbook = QtGui.QAction(Editor2)
        self.action_docbook.setObjectName(_fromUtf8("action_docbook"))
        self.action_tex = QtGui.QAction(Editor2)
        self.action_tex.setObjectName(_fromUtf8("action_tex"))
        self.action_txt = QtGui.QAction(Editor2)
        self.action_txt.setObjectName(_fromUtf8("action_txt"))
        self.action_rst = QtGui.QAction(Editor2)
        self.action_rst.setObjectName(_fromUtf8("action_rst"))
        self.action_mediawiki = QtGui.QAction(Editor2)
        self.action_mediawiki.setObjectName(_fromUtf8("action_mediawiki"))
        self.action_textile = QtGui.QAction(Editor2)
        self.action_textile.setObjectName(_fromUtf8("action_textile"))
        self.action_rtf = QtGui.QAction(Editor2)
        self.action_rtf.setObjectName(_fromUtf8("action_rtf"))
        self.action_org = QtGui.QAction(Editor2)
        self.action_org.setObjectName(_fromUtf8("action_org"))
        self.action_asciioc = QtGui.QAction(Editor2)
        self.action_asciioc.setObjectName(_fromUtf8("action_asciioc"))
        self.action_native = QtGui.QAction(Editor2)
        self.action_native.setObjectName(_fromUtf8("action_native"))
        self.actionOdt = QtGui.QAction(Editor2)
        self.actionOdt.setObjectName(_fromUtf8("actionOdt"))
        self.actionDocx = QtGui.QAction(Editor2)
        self.actionDocx.setObjectName(_fromUtf8("actionDocx"))
        self.actionEpub = QtGui.QAction(Editor2)
        self.actionEpub.setObjectName(_fromUtf8("actionEpub"))
        self.actionEpub3 = QtGui.QAction(Editor2)
        self.actionEpub3.setObjectName(_fromUtf8("actionEpub3"))
        self.actionLatex = QtGui.QAction(Editor2)
        self.actionLatex.setObjectName(_fromUtf8("actionLatex"))
        self.actionPlain = QtGui.QAction(Editor2)
        self.actionPlain.setObjectName(_fromUtf8("actionPlain"))
        self.actionNative = QtGui.QAction(Editor2)
        self.actionNative.setObjectName(_fromUtf8("actionNative"))
        self.actionJson = QtGui.QAction(Editor2)
        self.actionJson.setObjectName(_fromUtf8("actionJson"))
        self.actionOpendocument = QtGui.QAction(Editor2)
        self.actionOpendocument.setObjectName(_fromUtf8("actionOpendocument"))
        self.actionBeamer = QtGui.QAction(Editor2)
        self.actionBeamer.setObjectName(_fromUtf8("actionBeamer"))
        self.actionContext = QtGui.QAction(Editor2)
        self.actionContext.setObjectName(_fromUtf8("actionContext"))
        self.actionTexinfo = QtGui.QAction(Editor2)
        self.actionTexinfo.setObjectName(_fromUtf8("actionTexinfo"))
        self.actionPlain_2 = QtGui.QAction(Editor2)
        self.actionPlain_2.setObjectName(_fromUtf8("actionPlain_2"))
        self.actionMediawiki = QtGui.QAction(Editor2)
        self.actionMediawiki.setObjectName(_fromUtf8("actionMediawiki"))
        self.actionS5 = QtGui.QAction(Editor2)
        self.actionS5.setObjectName(_fromUtf8("actionS5"))
        self.actionMan = QtGui.QAction(Editor2)
        self.actionMan.setObjectName(_fromUtf8("actionMan"))
        self.actionDocbook = QtGui.QAction(Editor2)
        self.actionDocbook.setObjectName(_fromUtf8("actionDocbook"))
        self.actionSlidy = QtGui.QAction(Editor2)
        self.actionSlidy.setObjectName(_fromUtf8("actionSlidy"))
        self.actionSlideous = QtGui.QAction(Editor2)
        self.actionSlideous.setObjectName(_fromUtf8("actionSlideous"))
        self.actionDzslides = QtGui.QAction(Editor2)
        self.actionDzslides.setObjectName(_fromUtf8("actionDzslides"))
        self.actionRtf = QtGui.QAction(Editor2)
        self.actionRtf.setObjectName(_fromUtf8("actionRtf"))
        self.actionOrg = QtGui.QAction(Editor2)
        self.actionOrg.setObjectName(_fromUtf8("actionOrg"))
        self.actionAsciidoc = QtGui.QAction(Editor2)
        self.actionAsciidoc.setObjectName(_fromUtf8("actionAsciidoc"))
        self.actionRst = QtGui.QAction(Editor2)
        self.actionRst.setObjectName(_fromUtf8("actionRst"))
        self.actionOpciones = QtGui.QAction(Editor2)
        icon34 = QtGui.QIcon()
        icon34.addPixmap(QtGui.QPixmap(_fromUtf8("Resource/opciones.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionOpciones.setIcon(icon34)
        self.actionOpciones.setObjectName(_fromUtf8("actionOpciones"))
        self.menuPepe.addAction(self.actionArchivo)
        self.menuPepe.addAction(self.actionAbrir)
        self.menuPepe.addSeparator()
        self.menuPepe.addAction(self.actionGuardar)
        self.menuPepe.addAction(self.actionGuardar_Como)
        self.menuPepe.addSeparator()
        self.menuPepe.addAction(self.actionCerra)
        self.menuEditar.addAction(self.actionTitulo)
        self.menuEditar.addAction(self.actionCita)
        self.menuEditar.addAction(self.actionCodigo)
        self.menuEditar.addAction(self.actionLista_Numerica)
        self.menuEditar.addAction(self.actionLista)
        self.menuEditar.addAction(self.actionSeparador_linea)
        self.menuEditar.addAction(self.actionNegrita)
        self.menuEditar.addAction(self.actionCursiva)
        self.menuEditar.addSeparator()
        self.menuEditar.addAction(self.actionDeshacer)
        self.menuEditar.addAction(self.actionRehacer)
        self.menuEditar.addAction(self.actionCopiar)
        self.menuEditar.addAction(self.actionCortar)
        self.menuEditar.addAction(self.actionPegar)
        self.menuEditar.addSeparator()
        self.menuEditar.addAction(self.actionOpciones)
        self.menuInsertar.addAction(self.actionInsertar_Contenido)
        self.menuInsertar.addAction(self.actionInsertar_Utilidad)
        self.menuComunes.addAction(self.actionOdt)
        self.menuComunes.addAction(self.actionDocx)
        self.menuComunes.addAction(self.actionEpub)
        self.menuComunes.addAction(self.actionEpub3)
        self.menuComunes.addAction(self.actionLatex)
        self.menuComunes.addAction(self.actionPlain)
        self.menuComunes.addAction(self.actionS5)
        self.menuComunes.addAction(self.actionMan)
        self.menuComunes.addAction(self.actionRst)
        self.menuOtros.addAction(self.actionNative)
        self.menuOtros.addAction(self.actionJson)
        self.menuOtros.addAction(self.actionOpendocument)
        self.menuOtros.addAction(self.actionBeamer)
        self.menuOtros.addAction(self.actionContext)
        self.menuOtros.addAction(self.actionTexinfo)
        self.menuOtros.addAction(self.actionMediawiki)
        self.menuOtros.addAction(self.actionDocbook)
        self.menuOtros.addAction(self.actionSlidy)
        self.menuOtros.addAction(self.actionSlideous)
        self.menuOtros.addAction(self.actionDzslides)
        self.menuOtros.addAction(self.actionRtf)
        self.menuOtros.addAction(self.actionOrg)
        self.menuOtros.addAction(self.actionAsciidoc)
        self.menuExportar.addAction(self.menuComunes.menuAction())
        self.menuExportar.addAction(self.menuOtros.menuAction())
        self.menubar.addAction(self.menuPepe.menuAction())
        self.menubar.addAction(self.menuExportar.menuAction())
        self.menubar.addAction(self.menuEditar.menuAction())
        self.menubar.addAction(self.menuInsertar.menuAction())

        self.retranslateUi(Editor2)
        self.tabs.setCurrentIndex(0)
        QtCore.QObject.connect(self.link, QtCore.SIGNAL(_fromUtf8("clicked()")), Editor2.link)
        QtCore.QObject.connect(self.linea, QtCore.SIGNAL(_fromUtf8("clicked()")), Editor2.linea)
        QtCore.QObject.connect(self.negrita, QtCore.SIGNAL(_fromUtf8("clicked()")), Editor2.negrita)
        QtCore.QObject.connect(self.cursiva, QtCore.SIGNAL(_fromUtf8("clicked()")), Editor2.cursiva)
        QtCore.QObject.connect(self.actionAbrir, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.abrirArchivo)
        QtCore.QObject.connect(self.editando, QtCore.SIGNAL(_fromUtf8("textChanged()")), Editor2.cambia)
        QtCore.QObject.connect(self.html, QtCore.SIGNAL(_fromUtf8("clicked()")), Editor2.insUtilidad)
        QtCore.QObject.connect(self.actionGuardar, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.guardar)
        QtCore.QObject.connect(self.actionSeparador_linea, QtCore.SIGNAL(_fromUtf8("triggered()")), self.linea.click)
        QtCore.QObject.connect(self.actionNegrita, QtCore.SIGNAL(_fromUtf8("triggered()")), self.negrita.click)
        QtCore.QObject.connect(self.actionCursiva, QtCore.SIGNAL(_fromUtf8("triggered()")), self.cursiva.click)
        QtCore.QObject.connect(self.actionDeshacer, QtCore.SIGNAL(_fromUtf8("triggered()")), self.editando.undo)
        QtCore.QObject.connect(self.actionRehacer, QtCore.SIGNAL(_fromUtf8("triggered()")), self.editando.redo)
        QtCore.QObject.connect(self.actionCopiar, QtCore.SIGNAL(_fromUtf8("triggered()")), self.editando.copy)
        QtCore.QObject.connect(self.actionCortar, QtCore.SIGNAL(_fromUtf8("triggered()")), self.editando.cut)
        QtCore.QObject.connect(self.actionPegar, QtCore.SIGNAL(_fromUtf8("triggered()")), self.editando.paste)
        QtCore.QObject.connect(self.actionInsertar_Contenido, QtCore.SIGNAL(_fromUtf8("triggered()")), self.link.click)
        QtCore.QObject.connect(self.actionInsertar_Utilidad, QtCore.SIGNAL(_fromUtf8("triggered()")), self.html.click)
        QtCore.QObject.connect(self.actionArchivo, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.nuevo)
        QtCore.QObject.connect(self.guardar, QtCore.SIGNAL(_fromUtf8("clicked()")), Editor2.guardar)
        QtCore.QObject.connect(self.actionGuardar_Como, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.guardarEn)
        QtCore.QObject.connect(self.actionCerrar, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.close)
        QtCore.QObject.connect(self.actionCerra, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.close)
        QtCore.QObject.connect(self.actionOdt, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.odt)
        QtCore.QObject.connect(self.actionDocx, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.docx)
        QtCore.QObject.connect(self.actionEpub, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.epub)
        QtCore.QObject.connect(self.actionEpub3, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.epub3)
        QtCore.QObject.connect(self.actionLatex, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.latex)
        QtCore.QObject.connect(self.actionPlain, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.plain)
        QtCore.QObject.connect(self.actionS5, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.s5)
        QtCore.QObject.connect(self.actionMan, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.man)
        QtCore.QObject.connect(self.actionRst, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.rst)
        QtCore.QObject.connect(self.actionNative, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.native)
        QtCore.QObject.connect(self.actionJson, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.json)
        QtCore.QObject.connect(self.actionOpendocument, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.opendocument)
        QtCore.QObject.connect(self.actionBeamer, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.beamer)
        QtCore.QObject.connect(self.actionContext, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.context)
        QtCore.QObject.connect(self.actionTexinfo, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.texinfo)
        QtCore.QObject.connect(self.actionMediawiki, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.mediawiki)
        QtCore.QObject.connect(self.actionDocbook, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.docbook)
        QtCore.QObject.connect(self.actionSlidy, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.slidy)
        QtCore.QObject.connect(self.actionSlideous, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.slideous)
        QtCore.QObject.connect(self.actionDzslides, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.dzslides)
        QtCore.QObject.connect(self.actionRtf, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.rtf)
        QtCore.QObject.connect(self.actionOrg, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.org)
        QtCore.QObject.connect(self.actionAsciidoc, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.asciidoc)
        QtCore.QObject.connect(self.seleccion, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(QString)")), Editor2.seleccion)
        QtCore.QObject.connect(self.actionOpciones, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.opciones)
        QtCore.QObject.connect(self.actionTitulo, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.titulo)
        QtCore.QObject.connect(self.actionCita, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.cita)
        QtCore.QObject.connect(self.actionCodigo, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.codigo)
        QtCore.QObject.connect(self.actionLista_Numerica, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.listaN)
        QtCore.QObject.connect(self.actionLista, QtCore.SIGNAL(_fromUtf8("triggered()")), Editor2.lista)
        QtCore.QMetaObject.connectSlotsByName(Editor2)
        Editor2.setTabOrder(self.tabs, self.vistaHtml1)

    def retranslateUi(self, Editor2):
        Editor2.setWindowTitle(_translate("Editor2", "MarkYoun!", None))
        self.editando.setHtml(_translate("Editor2", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Nimbus Sans L\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600; font-style:italic;\"><br /></p></body></html>", None))
        self.tabs.setTabText(self.tabs.indexOf(self.editor), _translate("Editor2", "Editor", None))
        self.tabs.setTabText(self.tabs.indexOf(self.vistapreliminar), _translate("Editor2", "Ayudame a entender esto Youn!", None))
        self.seleccion.setItemText(0, _translate("Editor2", "Seleccionar", None))
        self.seleccion.setItemText(1, _translate("Editor2", "1- Titulo", None))
        self.seleccion.setItemText(2, _translate("Editor2", "2- Titulo", None))
        self.seleccion.setItemText(3, _translate("Editor2", "3- Titulo", None))
        self.seleccion.setItemText(4, _translate("Editor2", "1- Cita", None))
        self.seleccion.setItemText(5, _translate("Editor2", "2- Cita", None))
        self.seleccion.setItemText(6, _translate("Editor2", "3- Cita", None))
        self.seleccion.setItemText(7, _translate("Editor2", "Codigo", None))
        self.seleccion.setItemText(8, _translate("Editor2", "Lista N", None))
        self.seleccion.setItemText(9, _translate("Editor2", "Lista", None))
        self.link.setText(_translate("Editor2", "Cont", None))
        self.html.setText(_translate("Editor2", "Util", None))
        self.linea.setText(_translate("Editor2", "Linea", None))
        self.negrita.setText(_translate("Editor2", "Negrit", None))
        self.cursiva.setText(_translate("Editor2", "Cursiv", None))
        self.menuPepe.setTitle(_translate("Editor2", "Archivo", None))
        self.menuEditar.setTitle(_translate("Editor2", "Edicion", None))
        self.menuInsertar.setTitle(_translate("Editor2", "Insertar", None))
        self.menuExportar.setTitle(_translate("Editor2", "Exportar A", None))
        self.menuComunes.setTitle(_translate("Editor2", "Comunes", None))
        self.menuOtros.setTitle(_translate("Editor2", "Otros", None))
        self.actionArchivo.setText(_translate("Editor2", "Nuevo", None))
        self.actionArchivo.setShortcut(_translate("Editor2", "Ctrl+N", None))
        self.actionAbrir.setText(_translate("Editor2", "Abrir", None))
        self.actionAbrir.setShortcut(_translate("Editor2", "Ctrl+O", None))
        self.actionGuardar.setText(_translate("Editor2", "Guardar", None))
        self.actionGuardar.setShortcut(_translate("Editor2", "Ctrl+S", None))
        self.actionImprimir.setText(_translate("Editor2", "Imprimir", None))
        self.actionCerrar.setText(_translate("Editor2", "Cerrar", None))
        self.actionCerrar.setShortcut(_translate("Editor2", "Ctrl+W", None))
        self.actionTitulo.setText(_translate("Editor2", "Titulo", None))
        self.actionTitulo.setShortcut(_translate("Editor2", "Ctrl+T", None))
        self.actionCita.setText(_translate("Editor2", "Cita", None))
        self.actionCita.setShortcut(_translate("Editor2", "Ctrl+Y", None))
        self.actionCodigo.setText(_translate("Editor2", "Codigo", None))
        self.actionCodigo.setShortcut(_translate("Editor2", "Ctrl+U", None))
        self.actionLista_Numerica.setText(_translate("Editor2", "Lista Numerica", None))
        self.actionLista_Numerica.setShortcut(_translate("Editor2", "Ctrl+K", None))
        self.actionLista.setText(_translate("Editor2", "Lista", None))
        self.actionLista.setShortcut(_translate("Editor2", "Ctrl+L", None))
        self.actionSeparador_linea.setText(_translate("Editor2", "Separador-linea", None))
        self.actionSeparador_linea.setShortcut(_translate("Editor2", "Ctrl+H", None))
        self.actionNegrita.setText(_translate("Editor2", "Negrita", None))
        self.actionNegrita.setShortcut(_translate("Editor2", "Ctrl+B", None))
        self.actionCursiva.setText(_translate("Editor2", "Cursiva", None))
        self.actionCursiva.setShortcut(_translate("Editor2", "Ctrl+I", None))
        self.actionInsertar_Contenido.setText(_translate("Editor2", "Insertar Contenido", None))
        self.actionInsertar_Contenido.setShortcut(_translate("Editor2", "Ctrl+Q", None))
        self.actionInsertar_Utilidad.setText(_translate("Editor2", "Insertar Utilidad", None))
        self.actionInsertar_Utilidad.setShortcut(_translate("Editor2", "Ctrl+E", None))
        self.actionDeshacer.setText(_translate("Editor2", "Deshacer", None))
        self.actionDeshacer.setShortcut(_translate("Editor2", "Ctrl+Z", None))
        self.actionRehacer.setText(_translate("Editor2", "Rehacer", None))
        self.actionSeleccionar_todo.setText(_translate("Editor2", "Seleccionar todo", None))
        self.actionCopiar.setText(_translate("Editor2", "Copiar", None))
        self.actionCopiar.setShortcut(_translate("Editor2", "Ctrl+C", None))
        self.actionCortar.setText(_translate("Editor2", "Cortar", None))
        self.actionCortar.setShortcut(_translate("Editor2", "Ctrl+X", None))
        self.actionPegar.setText(_translate("Editor2", "Pegar", None))
        self.actionPegar.setShortcut(_translate("Editor2", "Ctrl+V", None))
        self.actionGuardar_Como.setText(_translate("Editor2", "Guardar Como", None))
        self.actionGuardar_Como.setShortcut(_translate("Editor2", "Ctrl+G", None))
        self.actionCerra.setText(_translate("Editor2", "Cerrar", None))
        self.actionCerra.setShortcut(_translate("Editor2", "Ctrl+W", None))
        self.action_odt.setText(_translate("Editor2", "Comunes", None))
        self.action_docx.setText(_translate("Editor2", ".docx", None))
        self.action_json.setText(_translate("Editor2", ".json", None))
        self.action_epub.setText(_translate("Editor2", ".epub", None))
        self.action_epub3.setText(_translate("Editor2", ".epub3", None))
        self.action_fb2.setText(_translate("Editor2", ".fb2", None))
        self.action_s6.setText(_translate("Editor2", ".s5", None))
        self.action_slidy.setText(_translate("Editor2", ".slidy", None))
        self.action_slideus.setText(_translate("Editor2", ".slideus", None))
        self.action_dzslides.setText(_translate("Editor2", ".dzslides", None))
        self.action_docbook.setText(_translate("Editor2", ".docbook", None))
        self.action_tex.setText(_translate("Editor2", ".latex", None))
        self.action_txt.setText(_translate("Editor2", ".plain", None))
        self.action_rst.setText(_translate("Editor2", ".rst", None))
        self.action_mediawiki.setText(_translate("Editor2", ".mediawiki", None))
        self.action_textile.setText(_translate("Editor2", ".textile", None))
        self.action_rtf.setText(_translate("Editor2", ".rtf", None))
        self.action_org.setText(_translate("Editor2", ".org", None))
        self.action_asciioc.setText(_translate("Editor2", ".asciioc", None))
        self.action_native.setText(_translate("Editor2", ".native", None))
        self.actionOdt.setText(_translate("Editor2", "odt", None))
        self.actionDocx.setText(_translate("Editor2", "docx", None))
        self.actionEpub.setText(_translate("Editor2", "epub", None))
        self.actionEpub3.setText(_translate("Editor2", "epub3", None))
        self.actionLatex.setText(_translate("Editor2", "latex", None))
        self.actionPlain.setText(_translate("Editor2", "plain", None))
        self.actionNative.setText(_translate("Editor2", "native", None))
        self.actionJson.setText(_translate("Editor2", "json", None))
        self.actionOpendocument.setText(_translate("Editor2", "opendocument", None))
        self.actionBeamer.setText(_translate("Editor2", "beamer", None))
        self.actionContext.setText(_translate("Editor2", "context", None))
        self.actionTexinfo.setText(_translate("Editor2", "texinfo", None))
        self.actionPlain_2.setText(_translate("Editor2", "plain", None))
        self.actionMediawiki.setText(_translate("Editor2", "mediawiki", None))
        self.actionS5.setText(_translate("Editor2", "s5", None))
        self.actionMan.setText(_translate("Editor2", "man", None))
        self.actionDocbook.setText(_translate("Editor2", "docbook", None))
        self.actionSlidy.setText(_translate("Editor2", "slidy", None))
        self.actionSlideous.setText(_translate("Editor2", "slideous", None))
        self.actionDzslides.setText(_translate("Editor2", "dzslides", None))
        self.actionRtf.setText(_translate("Editor2", "rtf", None))
        self.actionOrg.setText(_translate("Editor2", "org", None))
        self.actionAsciidoc.setText(_translate("Editor2", "asciidoc", None))
        self.actionRst.setText(_translate("Editor2", "rst", None))
        self.actionOpciones.setText(_translate("Editor2", "Opciones", None))

from PyQt4 import QtWebKit
